In [1]:
import pandas as pd

In [2]:
pd.read_csv('../data/13_diecasting_shot.csv')

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [3]:
df=pd.read_csv('../data/13_diecasting_shot.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   샷       200 non-null    int64
 1   설비ID    200 non-null    str
 2   실린더압력   186 non-null    float64
 3   주조압력    186 non-null    float64
 4   사이클타임   186 non-null    float64
 5   비스킷두께   186 non-null    float64
 6   형체력     186 non-null    float64
 7   품질등급    200 non-null    str
dtypes: float64(5), int64(1), str(2)
memory usage: 15.4 KB

In [5]:
df.columns

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급'], dtype='str')

In [6]:
df[['형체력','실린더압력']]

       형체력  실린더압력
0    258.0  214.0
1    257.0  217.0
2    254.0  214.0
3    253.0  217.0
4    254.0  217.0
..     ...    ...
195  381.0  264.0
196  355.0  265.0
197  354.0  113.0
198  372.0  264.0
199  237.0  108.0

[200 rows x 2 columns]

In [7]:
two_column=df[['형체력','실린더압력']]

In [8]:
two_column.shape

(200, 2)

In [9]:
list(df.columns)

['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급']

In [10]:
type(two_column)

pandas.DataFrame

In [11]:
one_column=df['형체력']

In [12]:
type(one_column)

pandas.Series

In [14]:
# one_column.
# two_column.

In [15]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [18]:
df.index

RangeIndex(start=0, stop=200, step=1)

In [19]:
# df[0]
df[0:3]

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품

In [20]:
df.iloc[0]

샷               1
설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [21]:
df.loc[0]

샷               1
설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [25]:
df_copy=df.set_index('샷')

In [26]:
df.index

RangeIndex(start=0, stop=200, step=1)

In [27]:
df_copy.index

RangeIndex(start=1, stop=201, step=1, name='샷')

In [28]:
df_copy

         설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
샷
1    DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
2    DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
3    DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
4    DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
5    DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..        ...    ...     ...     ...    ...    ...  ...
196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 7 columns]

In [29]:
df_copy.iloc[0]

설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 1, dtype: object

In [ ]:
df_copy.loc[0] #iloc와 다르다는 걸 보여주기 위해 일부러 에러 발생시킴

KeyError: 0

In [31]:
df_copy.loc[1]

설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 1, dtype: object

In [32]:
df

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [33]:
df.sort_values('형체력')

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
103  104  DIE-C-01    NaN     NaN     NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [34]:
df.sort_values('형체력', ascending=False)

       샷      설비ID  실린더압력   주조압력  사이클타임  비스킷두께    형체력 품질등급
171  172  DIE-A-01  265.0  595.0   36.1   17.0  384.0   양품
169  170  DIE-A-01  265.0  596.0   36.1   18.0  382.0   양품
166  167  DIE-B-01  264.0  595.0   35.9   18.0  382.0   양품
179  180  DIE-C-01  265.0  596.0   36.2   18.0  382.0   양품
168  169  DIE-A-01  265.0  596.0   36.1   18.0  382.0   양품
..   ...       ...    ...    ...    ...    ...    ...  ...
103  104  DIE-C-01    NaN    NaN    NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN    NaN    NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN    NaN    NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN    NaN    NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN    NaN    NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [35]:
df_sorted_by_body=df.sort_values('형체력', ascending=False)

In [36]:
df_sorted_by_body.index[:4]

Index([171, 169, 166, 179], dtype='int64')

In [37]:
df_sorted_by_body.index[:4].to_list()

[171, 169, 166, 179]

In [38]:
# 교재대로

In [39]:
df = pd.read_csv('..//data//13_diecasting_small.csv')

In [42]:
df.columns

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급'], dtype='str')

In [43]:
df_sorted_by_body = df.sort_values('형체력', ascending=False)

In [44]:
df_sorted_by_body.index

Index([22, 17, 27, 12, 19,  0, 11, 13, 14, 16, 18, 15,  8,  1, 21, 20, 26, 23,
       25, 24, 28,  7,  6,  3,  2,  5, 29, 10,  9,  4],
      dtype='int64')

In [45]:
df_sorted_by_body.index[:4]

Index([22, 17, 27, 12], dtype='int64')

In [46]:
df_sorted_by_body.index[:4].to_list()

[22, 17, 27, 12]

In [47]:
df_sorted_by_body.head()

     샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
22  23  DIE-B-01  265.0   595.0   33.9   19.0  359.0   주의
17  18  DIE-A-02  265.0   596.0   33.7   19.0  357.0   주의
27  28  DIE-C-01  265.0   595.0   33.8   19.0  355.0   주의
12  13  DIE-A-02  265.0   596.0   33.9   19.0  354.0   주의
19  20  DIE-A-01  216.0  1044.0   21.2   11.0  259.0   불량

In [48]:
df_sorted_by_body.reset_index()

    index   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0      22  23  DIE-B-01  265.0   595.0   33.9   19.0  359.0   주의
1      17  18  DIE-A-02  265.0   596.0   33.7   19.0  357.0   주의
2      27  28  DIE-C-01  265.0   595.0   33.8   19.0  355.0   주의
3      12  13  DIE-A-02  265.0   596.0   33.9   19.0  354.0   주의
4      19  20  DIE-A-01  216.0  1044.0   21.2   11.0  259.0   불량
5       0   1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
6      11  12  DIE-C-01  215.0  1038.0   20.9   11.0  258.0   양품
7      13  14  DIE-B-02  215.0  1039.0   20.9   11.0  258.0   양품
8      14  15  DIE-C-01  215.0  1041.0   21.3    4.0  258.0   불량
9      16  17  DIE-A-02  218.0  1054.0   21.0   11.0  258.0   양품
10     18  19  DIE-A-02  214.0  1038.0   20.8   11.0  257.0   양품
11     15  16  DIE-A-01  218.0  1053.0   20.8   12.0  257.0   양품
12      8   9  DIE-B-01  217.0  1052.0   20.6   11.0  257.0   양품
13      1   2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
14     21  22  DIE-B-01  218.0  1053.0   20.9   11.0  257.0   양품
15     20  21  DIE-C-01  214.0  1037.0   20.8   11.0  257.0   양품
16     26  27  DIE-C-01  217.0  1051.0   20.9   12.0  257.0   양품
17     23  24  DIE-A-01  214.0  1037.0   20.8   12.0  255.0   양품
18     25  26  DIE-A-01  218.0  1055.0   20.9   11.0  255.0   양품
19     24  25  DIE-A-02  219.0  1058.0   21.3    2.0  255.0   불량
20     28  29  DIE-B-02  218.0  1055.0   20.7   11.0  255.0   양품
21      7   8  DIE-C-01  235.0  1137.0   22.5    7.0  255.0   주의
22      6   7  DIE-B-02  217.0  1052.0   20.6   11.0  254.0   양품
23      3   4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
24      2   3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
25      5   6  DIE-A-02  217.0  1052.0   20.6   11.0  253.0   양품
26     29  30  DIE-A-02  218.0  1054.0   21.4    2.0  253.0   불량
27     10  11  DIE-A-01  215.0  1038.0   20.9   11.0  250.0   양품
28      9  10  DIE-C-01  214.0  1036.0   93.1   12.0  247.0   불량
29      4   5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [49]:
df_sorted_by_body.reset_index(drop=True)

     샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0   23  DIE-B-01  265.0   595.0   33.9   19.0  359.0   주의
1   18  DIE-A-02  265.0   596.0   33.7   19.0  357.0   주의
2   28  DIE-C-01  265.0   595.0   33.8   19.0  355.0   주의
3   13  DIE-A-02  265.0   596.0   33.9   19.0  354.0   주의
4   20  DIE-A-01  216.0  1044.0   21.2   11.0  259.0   불량
5    1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
6   12  DIE-C-01  215.0  1038.0   20.9   11.0  258.0   양품
7   14  DIE-B-02  215.0  1039.0   20.9   11.0  258.0   양품
8   15  DIE-C-01  215.0  1041.0   21.3    4.0  258.0   불량
9   17  DIE-A-02  218.0  1054.0   21.0   11.0  258.0   양품
10  19  DIE-A-02  214.0  1038.0   20.8   11.0  257.0   양품
11  16  DIE-A-01  218.0  1053.0   20.8   12.0  257.0   양품
12   9  DIE-B-01  217.0  1052.0   20.6   11.0  257.0   양품
13   2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
14  22  DIE-B-01  218.0  1053.0   20.9   11.0  257.0   양품
15  21  DIE-C-01  214.0  1037.0   20.8   11.0  257.0   양품
16  27  DIE-C-01  217.0  1051.0   20.9   12.0  257.0   양품
17  24  DIE-A-01  214.0  1037.0   20.8   12.0  255.0   양품
18  26  DIE-A-01  218.0  1055.0   20.9   11.0  255.0   양품
19  25  DIE-A-02  219.0  1058.0   21.3    2.0  255.0   불량
20  29  DIE-B-02  218.0  1055.0   20.7   11.0  255.0   양품
21   8  DIE-C-01  235.0  1137.0   22.5    7.0  255.0   주의
22   7  DIE-B-02  217.0  1052.0   20.6   11.0  254.0   양품
23   4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
24   3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
25   6  DIE-A-02  217.0  1052.0   20.6   11.0  253.0   양품
26  30  DIE-A-02  218.0  1054.0   21.4    2.0  253.0   불량
27  11  DIE-A-01  215.0  1038.0   20.9   11.0  250.0   양품
28  10  DIE-C-01  214.0  1036.0   93.1   12.0  247.0   불량
29   5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [50]:
re_numbering=df_sorted_by_body.reset_index(drop=True)

In [51]:
re_numbering.loc[0]

샷              23
설비ID     DIE-B-01
실린더압력       265.0
주조압력        595.0
사이클타임        33.9
비스킷두께        19.0
형체력         359.0
품질등급           주의
Name: 0, dtype: object

In [52]:
re_numbering.loc[0,'샷']

np.int64(23)

In [53]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [54]:
df.loc[0:4]

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [55]:
# 실습2 10시 30분까지

In [56]:
df.loc[0,"샷"]

np.int64(1)

In [59]:
df.iloc[0]['샷']

np.int64(1)

In [60]:
정렬 = df.sort_values("형체력", ascending=False)

In [61]:
print(int(정렬.loc[0, "샷"]))            # 1    이름표 0번 행
print(int(정렬.iloc[0]["샷"]))           # 23   맨 위 행
print(정렬.index[:3].tolist())           # [22, 17, 27]

1
23
[22, 17, 27]

In [62]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [63]:
df.loc[0:4]

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [64]:
df.loc[0:4, '형체력']

0    258.0
1    257.0
2    253.0
3    254.0
4    222.0
Name: 형체력, dtype: float64

In [65]:
df.columns

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급'], dtype='str')

In [66]:
df.loc[0:4, ['실린더압력', '형체력']]

   실린더압력    형체력
0  214.0  258.0
1  217.0  257.0
2  215.0  253.0
3  214.0  254.0
4  108.0  222.0

In [ ]:
# 1번 17샷부터 20샷까지의 설비ID, 사이클 타임, 품질등급이 나오도록 인덱싱 하세요

In [ ]:
# 2번 3,7,15 샷의 설비ID, 비스킷두께, 품질등급이 나오도록 인덱싱 하세요

In [70]:
df_shot_index=df.set_index('샷')

In [71]:
df_shot_index.loc[[3,7,15],['설비ID', '비스킷두께', '품질등급']]

        설비ID  비스킷두께 품질등급
샷
3   DIE-A-02   21.0   주의
7   DIE-B-02   11.0   양품
15  DIE-C-01    4.0   불량

In [72]:
# 7번 샷의 비스킷 두께만

In [74]:
df_2=df_shot_index.loc[[3,7,15],['설비ID', '비스킷두께', '품질등급']]

In [75]:
type(df_2)

pandas.DataFrame

In [76]:
df_2.index

Index([3, 7, 15], dtype='int64', name='샷')

In [77]:
df_2.loc[7,'비스킷두께']

np.float64(11.0)

In [73]:
# 7,15번의 설비아이디와 품질등급

In [79]:
df_2.loc[[7,15],['설비ID','품질등급']]

        설비ID 품질등급
샷
7   DIE-B-02   양품
15  DIE-C-01   불량

In [80]:
# 실습4 13_diecasting_shot.csv 파일로
# 11시 7분까지