In [1]:
import pandas as pd

In [2]:
df_left = pd.DataFrame({
    'Name': ['Harry Potter', 'David Baker', 'John Smith', 'Juan Martinez', 'Jane Connor'],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Female'],
    'Age': [23, 31, 22, 36, 30]
})

In [3]:
df_right = pd.DataFrame({
    'Name': ['John Smith', 'Alex Du Bois', 'Joanne Rowling', 'Jane Connor'],
    'Position': ['Intern', 'Team Lead', 'Manager', 'Manager'],
    'Wage': [25000, 75000, 90000, 70000]})

In [4]:
df_left

            Name  Gender  Age
0   Harry Potter    Male   23
1    David Baker    Male   31
2     John Smith    Male   22
3  Juan Martinez    Male   36
4    Jane Connor  Female   30

In [5]:
df_right

             Name   Position   Wage
0      John Smith     Intern  25000
1    Alex Du Bois  Team Lead  75000
2  Joanne Rowling    Manager  90000
3     Jane Connor    Manager  70000

In [6]:
pd.merge(df_left, df_right)

          Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [ ]:
pd.merge(df_left, df_right, on='Name')

          Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [8]:
pd.merge(df_left, df_right, on='Name', how='inner')

          Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [9]:
pd.merge(df_left, df_right, on='Name', how='left')

            Name  Gender  Age Position     Wage
0   Harry Potter    Male   23      NaN      NaN
1    David Baker    Male   31      NaN      NaN
2     John Smith    Male   22   Intern  25000.0
3  Juan Martinez    Male   36      NaN      NaN
4    Jane Connor  Female   30  Manager  70000.0

In [10]:
pd.merge(df_left, df_right, on='Name', how='right')

             Name  Gender   Age   Position   Wage
0      John Smith    Male  22.0     Intern  25000
1    Alex Du Bois     NaN   NaN  Team Lead  75000
2  Joanne Rowling     NaN   NaN    Manager  90000
3     Jane Connor  Female  30.0    Manager  70000

In [11]:
pd.merge(df_left, df_right, on='Name', how='outer')

             Name  Gender   Age   Position     Wage
0    Alex Du Bois     NaN   NaN  Team Lead  75000.0
1     David Baker    Male  31.0        NaN      NaN
2    Harry Potter    Male  23.0        NaN      NaN
3     Jane Connor  Female  30.0    Manager  70000.0
4  Joanne Rowling     NaN   NaN    Manager  90000.0
5      John Smith    Male  22.0     Intern  25000.0
6   Juan Martinez    Male  36.0        NaN      NaN