In [1]:
import pandas as pd

In [2]:
pd.read_csv('..//data//14_hydraulic - 복사본.csv')

    냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
0      고장  고부하   정상  35.6  0.577  160.67  39.6     정상
1      고장  저부하   정상  47.5  0.604  158.65  17.6     정상
2      고장  저부하   정상  50.7  0.640  157.76  18.7     정상
3      고장  저부하   정상  51.7  0.635  157.54  19.6     정상
4      고장  저부하   정상  52.4  0.635  157.36  21.1     정상
..    ...  ...  ...   ...    ...     ...   ...    ...
115    정상  고부하   지연  35.7  0.546  160.81  47.0     고장
116    정상  고부하   정상  35.6  0.544  160.68  46.8     고장
117    정상  고부하   지연  35.5  0.558  161.32  46.6     정상
118    정상  고부하   경미  35.4  0.547  161.26  46.6     정상
119    정상  고부하   정상  35.3  0.547  161.22  46.6     정상

[120 rows x 8 columns]

In [3]:
df=pd.read_csv('..//data//14_hydraulic - 복사본.csv')

In [4]:
qc=pd.read_csv('..//data//14_hydraulic_qc copy.csv')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   냉각기상태   120 non-null    str
 1   운전부하    120 non-null    str
 2   밸브상태    120 non-null    str
 3   온도      120 non-null    float64
 4   진동      120 non-null    float64
 5   압력      120 non-null    float64
 6   냉각효율    120 non-null    float64
 7   result  120 non-null    str
dtypes: float64(4), str(4)
memory usage: 10.8 KB

In [6]:
df.head()

  냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
0    고장  고부하   정상  35.6  0.577  160.67  39.6     정상
1    고장  저부하   정상  47.5  0.604  158.65  17.6     정상
2    고장  저부하   정상  50.7  0.640  157.76  18.7     정상
3    고장  저부하   정상  51.7  0.635  157.54  19.6     정상
4    고장  저부하   정상  52.4  0.635  157.36  21.1     정상

In [7]:
df.describe()

               온도          진동          압력        냉각효율
count  120.000000  120.000000  120.000000  120.000000
mean    45.339167    0.615633  161.001667   31.440833
std      8.042182    0.063953    5.392362   11.553198
min     35.300000    0.530000  156.080000   17.600000
25%     36.200000    0.554250  158.205000   20.175000
50%     44.800000    0.609500  159.095000   27.450000
75%     53.950000    0.656000  161.015000   46.700000
max     57.800000    0.779000  180.920000   47.800000

In [8]:
qc.head()

  검사결과    온도     진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0   합격  44.7  0.615  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1   합격  41.9  0.611  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2   합격  40.1  0.599  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3   합격  38.9  0.587  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4   합격  38.0  0.585  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0

In [9]:
qc.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   검사결과    200 non-null    str
 1   온도      200 non-null    float64
 2   진동      200 non-null    float64
 3   압력      200 non-null    float64
 4   냉각효율    200 non-null    float64
 5   유량      200 non-null    float64
 6   모터전력    200 non-null    float64
 7   효율지수    200 non-null    float64
 8   보조압력    200 non-null    float64
 9   냉각출력    200 non-null    float64
 10  배유온도    200 non-null    float64
dtypes: float64(10), str(1)
memory usage: 18.5 KB

In [10]:
qc.describe()

,온도,진동,압력,냉각효율,유량,모터전력,효율지수,보조압력,냉각출력,배유온도
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,37.107000,0.563510,161.484000,45.242000,6.528300,2543.482500,57.551500,110.005450,1.951950,42.641000
std,4.846918,0.043775,2.549799,6.543856,0.711903,26.043098,6.054767,2.835714,0.190505,4.400893
min,35.300000,0.524000,156.140000,18.800000,3.220000,2414.700000,29.000000,105.240000,1.070000,40.900000
25%,35.500000,0.546750,161.000000,46.600000,6.680000,2539.550000,58.800000,109.420000,1.990000,41.100000
50%,35.600000,0.553000,161.030000,46.900000,6.690000,2542.350000,58.900000,109.575000,2.000000,41.200000
75%,36.200000,0.562000,161.160000,47.200000,6.700000,2545.000000,59.100000,109.610000,2.010000,41.900000
max,57.500000,0.799000,173.320000,47.800000,6.720000,2651.700000,59.700000,123.100000,2.020000,60.800000

In [12]:
df['냉각기상태'].value_counts()

냉각기상태
고장    40
저하    40
정상    40
Name: count, dtype: int64

In [13]:
df['밸브상태'].value_counts()

밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64

In [15]:
df['result'].value_counts(normalize=True)

result
정상    0.558333
고장    0.441667
Name: proportion, dtype: float64

In [16]:
pd.set_option("display.precision", 3)

In [17]:
df['result'].value_counts(normalize=True)

result
정상    0.558
고장    0.442
Name: proportion, dtype: float64

In [18]:
# 실습1 9시 20분까지

In [19]:
print(df["밸브상태"].value_counts())
# 정상 61 · 지연 20 · 경미 20 · 심각 19
print(df["운전부하"].value_counts())
# 고부하 60 · 저부하 60
print(df["밸브상태"].value_counts().sum())     # 120

밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64
운전부하
고부하    60
저부하    60
Name: count, dtype: int64
120

In [20]:
# 실습2 9시 25분까지

In [21]:
print(qc.shape)                                   # (200, 11)
print(qc["검사결과"].value_counts())               # 합격 188 · 불합격 12
print(qc["검사결과"].value_counts(normalize=True))

(200, 11)
검사결과
합격     188
불합격     12
Name: count, dtype: int64
검사결과
합격     0.94
불합격    0.06
Name: proportion, dtype: float64

In [22]:
df['온도']

0      35.6
1      47.5
2      50.7
3      51.7
4      52.4
       ...
115    35.7
116    35.6
117    35.5
118    35.4
119    35.3
Name: 온도, Length: 120, dtype: float64

In [23]:
df['온도'].values

array([35.6, 47.5, 50.7, 51.7, 52.4, 53.1, 53.5, 53.7, 53.9, 53.9, 54.1,
       54.3, 54.2, 54.2, 54.5, 54.4, 54.6, 55. , 54.5, 54.4, 56. , 56.6,
       56.8, 57.1, 56.3, 56. , 56. , 57.1, 57.6, 57.5, 57.8, 57.2, 57. ,
       56.3, 57.2, 57.2, 57.2, 57.1, 56.6, 55.9, 51.2, 48.1, 47.4, 47.1,
       46.9, 46.8, 46.7, 46.6, 46.5, 46.5, 46.4, 46.1, 46. , 46. , 45.9,
       45.7, 45.7, 45.6, 45.4, 45. , 44.8, 44.8, 44.6, 44.6, 44.6, 44.4,
       44.1, 44.1, 44.1, 44.1, 44.3, 44.3, 44.3, 44. , 44. , 44.1, 44.1,
       44.4, 44.5, 44.8, 36.2, 35.5, 35.4, 35.4, 35.5, 35.5, 35.5, 35.5,
       35.4, 35.5, 35.6, 35.7, 35.7, 35.9, 35.9, 36.1, 36.2, 36.3, 36.2,
       36.4, 36.4, 36.2, 36.1, 36.2, 36.3, 36.2, 36.3, 36.3, 36.3, 36.2,
       36.2, 36.1, 36. , 35.9, 35.8, 35.7, 35.6, 35.5, 35.4, 35.3])

In [25]:
df['온도'].min()

np.float64(35.3)

In [26]:
df['온도'].max()

np.float64(57.8)

In [27]:
df['온도'].value_counts()

온도
36.2    8
35.5    7
44.1    6
36.3    5
57.2    4
       ..
45.0    1
44.5    1
36.0    1
35.8    1
35.3    1
Name: count, Length: 62, dtype: int64

In [29]:
pd.cut(df['온도'], bins=[0,40,50,200])

0        (0, 40]
1       (40, 50]
2      (50, 200]
3      (50, 200]
4      (50, 200]
         ...
115      (0, 40]
116      (0, 40]
117      (0, 40]
118      (0, 40]
119      (0, 40]
Name: 온도, Length: 120, dtype: category
Categories (3, interval[int64, right]): [(0, 40] < (40, 50] < (50, 200]]

In [30]:
pd.cut(df['온도'], bins=[0,40,50,200], labels=['낮음','보통','높음'])

0      낮음
1      보통
2      높음
3      높음
4      높음
       ..
115    낮음
116    낮음
117    낮음
118    낮음
119    낮음
Name: 온도, Length: 120, dtype: category
Categories (3, str): ['낮음' < '보통' < '높음']

In [31]:
band=pd.cut(df['온도'], bins=[0,40,50,200], labels=['낮음','보통','높음'])

In [32]:
band.value_counts()

온도
낮음    41
보통    40
높음    39
Name: count, dtype: int64

In [33]:
# 실습3 10시 27분까지

In [34]:
print(df["진동"].min(), df["진동"].max())      # 0.53 0.779

0.53 0.779

In [35]:
band_v = pd.cut(df["진동"], bins=[0, 0.6, 0.7, 10],
                labels=["약함", "보통", "강함"])

In [36]:
print(band_v.value_counts())
# 보통 55 · 약함 48 · 강함 17

진동
보통    55
약함    48
강함    17
Name: count, dtype: int64

In [37]:
print(band_v.value_counts().sum())            # 120

120

In [38]:
band_x = pd.cut(df["진동"], bins=[0, 0.62, 0.7, 10],
                labels=["약함", "보통", "강함"])
print(band_x.value_counts().to_dict())

{'약함': 75, '보통': 28, '강함': 17}

In [39]:
df.head()

  냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
0    고장  고부하   정상  35.6  0.577  160.67  39.6     정상
1    고장  저부하   정상  47.5  0.604  158.65  17.6     정상
2    고장  저부하   정상  50.7  0.640  157.76  18.7     정상
3    고장  저부하   정상  51.7  0.635  157.54  19.6     정상
4    고장  저부하   정상  52.4  0.635  157.36  21.1     정상

In [40]:
df['냉각기상태'].value_counts()

냉각기상태
고장    40
저하    40
정상    40
Name: count, dtype: int64

In [41]:
df.groupby('냉각기상태')

In [42]:
import numpy as np

In [45]:
list(df.groupby('냉각기상태'))

[('고장',
     냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
  0     고장  고부하   정상  35.6  0.577  160.67  39.6     정상
  1     고장  저부하   정상  47.5  0.604  158.65  17.6     정상
  2     고장  저부하   정상  50.7  0.640  157.76  18.7     정상
  3     고장  저부하   정상  51.7  0.635  157.54  19.6     정상
  4     고장  저부하   정상  52.4  0.635  157.36  21.1     정상
  5     고장  저부하   정상  53.1  0.648  157.20  20.9     정상
  6     고장  저부하   정상  53.5  0.666  157.07  20.1     정상
  7     고장  저부하   정상  53.7  0.656  157.09  19.6     정상
  8     고장  저부하   정상  53.9  0.660  156.95  19.6     정상
  9     고장  저부하   정상  53.9  0.668  157.07  19.6     정상
  10    고장  저부하   정상  54.1  0.667  157.00  20.0     정상
  11    고장  저부하   정상  54.3  0.662  157.01  19.9     정상
  12    고장  저부하   지연  54.2  0.661  156.20  19.9     고장
  13    고장  저부하   경미  54.2  0.648  156.14  19.9     고장
  14    고장  저부하   심각  54.5  0.657  156.54  20.1     고장
  15    고장  저부하   경미  54.4  0.659  156.49  20.0     고장
  16    고장  저부하   심각  54.6  0.666  157.07  20.2     정상
  17    고장  저부하   경미  55.0  0.656  156.79  20.6     정상
  18    고장  저부하   정상  54.5  0.676  156.82  20.4     정상
  19    고장  고부하   심각  54.4  0.749  173.28  20.2     고장
  20    고장  고부하   경미  56.0  0.779  180.41  20.8     고장
  21    고장  고부하   심각  56.6  0.739  180.70  19.7     고장
  22    고장  고부하   경미  56.8  0.733  172.86  19.0     고장
  23    고장  저부하   정상  57.1  0.725  156.08  18.8     정상
  24    고장  저부하   지연  56.3  0.654  156.40  20.3     정상
  25    고장  고부하   정상  56.0  0.733  180.92  20.6     정상
  26    고장  고부하   심각  56.0  0.741  173.03  20.0     고장
  27    고장  고부하   경미  57.1  0.759  173.06  19.3     고장
  28    고장  고부하   심각  57.6  0.719  172.94  18.9     고장
  29    고장  고부하   지연  57.5  0.732  172.87  19.2     고장
  30    고장  고부하   정상  57.8  0.725  172.72  19.2     고장
  31    고장  고부하   지연  57.2  0.774  173.32  19.1     정상
  32    고장  저부하   정상  57.0  0.741  156.60  19.0     정상
  33    고장  고부하   심각  56.3  0.728  173.06  19.6     고장
  34    고장  고부하   지연  57.2  0.706  166.57  18.8     고장
  35    고장  고부하   정상  57.2  0.725  172.58  18.9     고장
  36    고장  고부하   지연  57.2  0.697  166.75  18.8     고장
  37    고장  고부하   정상  57.1  0.719  172.86  18.7     고장
  38    고장  저부하   지연  56.6  0.660  156.31  18.6     정상
  39    고장  저부하   정상  55.9  0.646  156.32  20.1     정상),
 ('저하',
     냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
  40    저하  저부하   정상  51.2  0.592  157.09  27.0     정상
  41    저하  저부하   정상  48.1  0.595  157.86  26.3     정상
  42    저하  저부하   정상  47.4  0.596  158.09  26.3     정상
  43    저하  저부하   정상  47.1  0.597  158.16  26.3     정상
  44    저하  저부하   정상  46.9  0.594  158.24  26.2     정상
  45    저하  저부하   정상  46.8  0.593  158.25  26.2     정상
  46    저하  저부하   정상  46.7  0.604  158.30  26.4     정상
  47    저하  저부하   정상  46.6  0.601  158.32  26.3     정상
  48    저하  저부하   정상  46.5  0.614  158.30  26.5     정상
  49    저하  저부하   정상  46.5  0.610  158.35  26.8     정상
  50    저하  저부하   정상  46.4  0.622  158.39  26.5     정상
  51    저하  저부하   심각  46.1  0.617  158.10  26.7     고장
  52    저하  저부하   경미  46.0  0.627  157.92  26.9     고장
  53    저하  저부하   정상  46.0  0.622  157.87  27.2     고장
  54    저하  저부하   지연  45.9  0.629  158.30  27.4     고장
  55    저하  저부하   정상  45.7  0.629  158.24  27.7     고장
  56    저하  저부하   지연  45.7  0.624  158.78  28.2     정상
  57    저하  저부하   정상  45.6  0.611  158.64  28.1     정상
  58    저하  저부하   정상  45.4  0.604  158.65  27.8     정상
  59    저하  저부하   지연  45.0  0.614  158.22  27.8     고장
  60    저하  저부하   정상  44.8  0.614  158.12  27.7     고장
  61    저하  저부하   지연  44.8  0.616  158.55  27.5     고장
  62    저하  저부하   정상  44.6  0.613  158.48  27.8     고장
  63    저하  저부하   심각  44.6  0.609  159.12  27.6     정상
  64    저하  저부하   경미  44.6  0.612  158.96  27.6     정상
  65    저하  저부하   정상  44.4  0.603  158.93  27.6     정상
  66    저하  고부하   지연  44.1  0.623  158.45  27.4     고장
  67    저하  고부하   정상  44.1  0.616  158.38  27.3     고장
  68    저하  저부하   심각  44.1  0.617  158.85  27.9     고장
  69    저하  저부하   경미  44.1  0.613  158.69  27.5     고장
  70    저하  저부하   심각  44.3  0.612  159.23  27.3     정상
  71    저하  저부하   경미  44.3  0.602  159.05  27.4     정상
  72    저하  저부하   정상  44.3  0.604  158.99  27.5     정상
  73    저하  고부하   지연  44.0  0.608  158.52  27.3     고장
  74    저하  저부하   경미  44.0  0.618  158.46  27.7     고장
  75    저하  저부하   심각  44.1  0.606  158.85  27.8     고장
  76    저하  저부하   경미  44.1  0.609  158.69  27.2     고장
  77    저하  저부하   심각  44.4  0.612  159.24  27.5     정상
  78    저하  저부하   경미  44.5  0.607  159.07  27.6     정상
  79    저하  저부하   정상  44.8  0.596  158.96  27.9     정상),
 ('정상',
      냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
  80     정상  고부하   정상  36.2  0.563  160.72  47.3     정상
  81     정상  고부하   정상  35.5  0.561  160.97  46.5     정상
  82     정상  고부하   정상  35.4  0.566  161.00  46.6     정상
  83     정상  고부하   정상  35.4  0.561  161.04  46.4     정상
  84     정상  고부하   정상  35.5  0.562  161.01  46.7     정상
  85     정상  고부하   정상  35.5  0.564  161.03  46.7     정상
  86     정상  고부하   정상  35.5  0.561  161.03  46.5     정상
  87     정상  고부하   정상  35.5  0.555  161.04  46.7     정상
  88     정상  고부하   정상  35.4  0.552  161.04  46.9     정상
  89     정상  고부하   정상  35.5  0.557  161.04  47.2     정상
  90     정상  고부하   정상  35.6  0.552  161.16  47.4     정상
  91     정상  고부하   지연  35.7  0.551  160.56  47.2     고장
  92     정상  고부하   경미  35.7  0.539  160.49  47.8     고장
  93     정상  고부하   심각  35.9  0.539  160.91  47.3     고장
  94     정상  고부하   경미  35.9  0.542  160.69  47.4     고장
  95     정상  고부하   심각  36.1  0.551  161.27  47.5     정상
  96     정상  고부하   경미  36.2  0.548  161.08  47.5     정상
  97     정상  고부하   정상  36.3  0.549  161.01  47.3     정상
  98     정상  고부하   심각  36.2  0.547  160.45  47.0     고장
  99     정상  고부하   경미  36.4  0.546  160.22  46.7     고장
  100    정상  고부하   심각  36.4  0.552  160.70  46.3     고장
  101    정상  고부하   경미  36.2  0.550  160.61  46.7     고장
  102    정상  고부하   정상  36.1  0.537  160.96  46.8     정상
  103    정상  고부하   지연  36.2  0.536  161.11  47.2     정상
  104    정상  고부하   정상  36.3  0.530  160.92  47.4     정상
  105    정상  고부하   심각  36.2  0.540  160.48  47.0     고장
  106    정상  고부하   경미  36.3  0.537  160.31  46.8     고장
  107    정상  고부하   정상  36.3  0.541  160.47  46.5     고장
  108    정상  고부하   지연  36.3  0.540  160.64  46.9     고장
  109    정상  고부하   정상  36.2  0.549  160.58  46.8     고장
  110    정상  고부하   지연  36.2  0.544  161.10  47.1     정상
  111    정상  고부하   정상  36.1  0.546  161.00  47.1     정상
  112    정상  고부하   심각  36.0  0.545  160.61  47.5     고장
  113    정상  고부하   지연  35.9  0.550  160.53  46.9     고장
  114    정상  고부하   정상  35.8  0.541  160.41  47.0     고장
  115    정상  고부하   지연  35.7  0.546  160.81  47.0     고장
  116    정상  고부하   정상  35.6  0.544  160.68  46.8     고장
  117    정상  고부하   지연  35.5  0.558  161.32  46.6     정상
  118    정상  고부하   경미  35.4  0.547  161.26  46.6     정상
  119    정상  고부하   정상  35.3  0.547  161.22  46.6     정상)]

In [46]:
list(df.groupby('냉각기상태'))[0]

('고장',
    냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
 0     고장  고부하   정상  35.6  0.577  160.67  39.6     정상
 1     고장  저부하   정상  47.5  0.604  158.65  17.6     정상
 2     고장  저부하   정상  50.7  0.640  157.76  18.7     정상
 3     고장  저부하   정상  51.7  0.635  157.54  19.6     정상
 4     고장  저부하   정상  52.4  0.635  157.36  21.1     정상
 5     고장  저부하   정상  53.1  0.648  157.20  20.9     정상
 6     고장  저부하   정상  53.5  0.666  157.07  20.1     정상
 7     고장  저부하   정상  53.7  0.656  157.09  19.6     정상
 8     고장  저부하   정상  53.9  0.660  156.95  19.6     정상
 9     고장  저부하   정상  53.9  0.668  157.07  19.6     정상
 10    고장  저부하   정상  54.1  0.667  157.00  20.0     정상
 11    고장  저부하   정상  54.3  0.662  157.01  19.9     정상
 12    고장  저부하   지연  54.2  0.661  156.20  19.9     고장
 13    고장  저부하   경미  54.2  0.648  156.14  19.9     고장
 14    고장  저부하   심각  54.5  0.657  156.54  20.1     고장
 15    고장  저부하   경미  54.4  0.659  156.49  20.0     고장
 16    고장  저부하   심각  54.6  0.666  157.07  20.2     정상
 17    고장  저부하   경미  55.0  0.656  156.79  20.6     정상
 18    고장  저부하   정상  54.5  0.676  156.82  20.4     정상
 19    고장  고부하   심각  54.4  0.749  173.28  20.2     고장
 20    고장  고부하   경미  56.0  0.779  180.41  20.8     고장
 21    고장  고부하   심각  56.6  0.739  180.70  19.7     고장
 22    고장  고부하   경미  56.8  0.733  172.86  19.0     고장
 23    고장  저부하   정상  57.1  0.725  156.08  18.8     정상
 24    고장  저부하   지연  56.3  0.654  156.40  20.3     정상
 25    고장  고부하   정상  56.0  0.733  180.92  20.6     정상
 26    고장  고부하   심각  56.0  0.741  173.03  20.0     고장
 27    고장  고부하   경미  57.1  0.759  173.06  19.3     고장
 28    고장  고부하   심각  57.6  0.719  172.94  18.9     고장
 29    고장  고부하   지연  57.5  0.732  172.87  19.2     고장
 30    고장  고부하   정상  57.8  0.725  172.72  19.2     고장
 31    고장  고부하   지연  57.2  0.774  173.32  19.1     정상
 32    고장  저부하   정상  57.0  0.741  156.60  19.0     정상
 33    고장  고부하   심각  56.3  0.728  173.06  19.6     고장
 34    고장  고부하   지연  57.2  0.706  166.57  18.8     고장
 35    고장  고부하   정상  57.2  0.725  172.58  18.9     고장
 36    고장  고부하   지연  57.2  0.697  166.75  18.8     고장
 37    고장  고부하   정상  57.1  0.719  172.86  18.7     고장
 38    고장  저부하   지연  56.6  0.660  156.31  18.6     정상
 39    고장  저부하   정상  55.9  0.646  156.32  20.1     정상)

In [47]:
type(list(df.groupby('냉각기상태'))[0])

tuple

In [49]:
list(df.groupby('냉각기상태'))[0][0]

'고장'

In [50]:
list(df.groupby('냉각기상태'))[0][1]

   냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
0     고장  고부하   정상  35.6  0.577  160.67  39.6     정상
1     고장  저부하   정상  47.5  0.604  158.65  17.6     정상
2     고장  저부하   정상  50.7  0.640  157.76  18.7     정상
3     고장  저부하   정상  51.7  0.635  157.54  19.6     정상
4     고장  저부하   정상  52.4  0.635  157.36  21.1     정상
5     고장  저부하   정상  53.1  0.648  157.20  20.9     정상
6     고장  저부하   정상  53.5  0.666  157.07  20.1     정상
7     고장  저부하   정상  53.7  0.656  157.09  19.6     정상
8     고장  저부하   정상  53.9  0.660  156.95  19.6     정상
9     고장  저부하   정상  53.9  0.668  157.07  19.6     정상
10    고장  저부하   정상  54.1  0.667  157.00  20.0     정상
11    고장  저부하   정상  54.3  0.662  157.01  19.9     정상
12    고장  저부하   지연  54.2  0.661  156.20  19.9     고장
13    고장  저부하   경미  54.2  0.648  156.14  19.9     고장
14    고장  저부하   심각  54.5  0.657  156.54  20.1     고장
15    고장  저부하   경미  54.4  0.659  156.49  20.0     고장
16    고장  저부하   심각  54.6  0.666  157.07  20.2     정상
17    고장  저부하   경미  55.0  0.656  156.79  20.6     정상
18    고장  저부하   정상  54.5  0.676  156.82  20.4     정상
19    고장  고부하   심각  54.4  0.749  173.28  20.2     고장
20    고장  고부하   경미  56.0  0.779  180.41  20.8     고장
21    고장  고부하   심각  56.6  0.739  180.70  19.7     고장
22    고장  고부하   경미  56.8  0.733  172.86  19.0     고장
23    고장  저부하   정상  57.1  0.725  156.08  18.8     정상
24    고장  저부하   지연  56.3  0.654  156.40  20.3     정상
25    고장  고부하   정상  56.0  0.733  180.92  20.6     정상
26    고장  고부하   심각  56.0  0.741  173.03  20.0     고장
27    고장  고부하   경미  57.1  0.759  173.06  19.3     고장
28    고장  고부하   심각  57.6  0.719  172.94  18.9     고장
29    고장  고부하   지연  57.5  0.732  172.87  19.2     고장
30    고장  고부하   정상  57.8  0.725  172.72  19.2     고장
31    고장  고부하   지연  57.2  0.774  173.32  19.1     정상
32    고장  저부하   정상  57.0  0.741  156.60  19.0     정상
33    고장  고부하   심각  56.3  0.728  173.06  19.6     고장
34    고장  고부하   지연  57.2  0.706  166.57  18.8     고장
35    고장  고부하   정상  57.2  0.725  172.58  18.9     고장
36    고장  고부하   지연  57.2  0.697  166.75  18.8     고장
37    고장  고부하   정상  57.1  0.719  172.86  18.7     고장
38    고장  저부하   지연  56.6  0.660  156.31  18.6     정상
39    고장  저부하   정상  55.9  0.646  156.32  20.1     정상

In [51]:
list(df.groupby('냉각기상태'))[0][1].describe()

           온도      진동       압력    냉각효율
count  40.000  40.000   40.000  40.000
mean   54.667   0.688  163.676  20.125
std     3.760   0.048    8.638   3.245
min    35.600   0.577  156.080  17.600
25%    54.050   0.656  156.812  19.000
50%    55.450   0.667  157.450  19.650
75%    57.025   0.729  172.863  20.125
max    57.800   0.779  180.920  39.600

In [52]:
list(df.groupby('냉각기상태'))[1]

('저하',
    냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
 40    저하  저부하   정상  51.2  0.592  157.09  27.0     정상
 41    저하  저부하   정상  48.1  0.595  157.86  26.3     정상
 42    저하  저부하   정상  47.4  0.596  158.09  26.3     정상
 43    저하  저부하   정상  47.1  0.597  158.16  26.3     정상
 44    저하  저부하   정상  46.9  0.594  158.24  26.2     정상
 45    저하  저부하   정상  46.8  0.593  158.25  26.2     정상
 46    저하  저부하   정상  46.7  0.604  158.30  26.4     정상
 47    저하  저부하   정상  46.6  0.601  158.32  26.3     정상
 48    저하  저부하   정상  46.5  0.614  158.30  26.5     정상
 49    저하  저부하   정상  46.5  0.610  158.35  26.8     정상
 50    저하  저부하   정상  46.4  0.622  158.39  26.5     정상
 51    저하  저부하   심각  46.1  0.617  158.10  26.7     고장
 52    저하  저부하   경미  46.0  0.627  157.92  26.9     고장
 53    저하  저부하   정상  46.0  0.622  157.87  27.2     고장
 54    저하  저부하   지연  45.9  0.629  158.30  27.4     고장
 55    저하  저부하   정상  45.7  0.629  158.24  27.7     고장
 56    저하  저부하   지연  45.7  0.624  158.78  28.2     정상
 57    저하  저부하   정상  45.6  0.611  158.64  28.1     정상
 58    저하  저부하   정상  45.4  0.604  158.65  27.8     정상
 59    저하  저부하   지연  45.0  0.614  158.22  27.8     고장
 60    저하  저부하   정상  44.8  0.614  158.12  27.7     고장
 61    저하  저부하   지연  44.8  0.616  158.55  27.5     고장
 62    저하  저부하   정상  44.6  0.613  158.48  27.8     고장
 63    저하  저부하   심각  44.6  0.609  159.12  27.6     정상
 64    저하  저부하   경미  44.6  0.612  158.96  27.6     정상
 65    저하  저부하   정상  44.4  0.603  158.93  27.6     정상
 66    저하  고부하   지연  44.1  0.623  158.45  27.4     고장
 67    저하  고부하   정상  44.1  0.616  158.38  27.3     고장
 68    저하  저부하   심각  44.1  0.617  158.85  27.9     고장
 69    저하  저부하   경미  44.1  0.613  158.69  27.5     고장
 70    저하  저부하   심각  44.3  0.612  159.23  27.3     정상
 71    저하  저부하   경미  44.3  0.602  159.05  27.4     정상
 72    저하  저부하   정상  44.3  0.604  158.99  27.5     정상
 73    저하  고부하   지연  44.0  0.608  158.52  27.3     고장
 74    저하  저부하   경미  44.0  0.618  158.46  27.7     고장
 75    저하  저부하   심각  44.1  0.606  158.85  27.8     고장
 76    저하  저부하   경미  44.1  0.609  158.69  27.2     고장
 77    저하  저부하   심각  44.4  0.612  159.24  27.5     정상
 78    저하  저부하   경미  44.5  0.607  159.07  27.6     정상
 79    저하  저부하   정상  44.8  0.596  158.96  27.9     정상)

In [53]:
list(df.groupby('냉각기상태'))[2]

('정상',
     냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
 80     정상  고부하   정상  36.2  0.563  160.72  47.3     정상
 81     정상  고부하   정상  35.5  0.561  160.97  46.5     정상
 82     정상  고부하   정상  35.4  0.566  161.00  46.6     정상
 83     정상  고부하   정상  35.4  0.561  161.04  46.4     정상
 84     정상  고부하   정상  35.5  0.562  161.01  46.7     정상
 85     정상  고부하   정상  35.5  0.564  161.03  46.7     정상
 86     정상  고부하   정상  35.5  0.561  161.03  46.5     정상
 87     정상  고부하   정상  35.5  0.555  161.04  46.7     정상
 88     정상  고부하   정상  35.4  0.552  161.04  46.9     정상
 89     정상  고부하   정상  35.5  0.557  161.04  47.2     정상
 90     정상  고부하   정상  35.6  0.552  161.16  47.4     정상
 91     정상  고부하   지연  35.7  0.551  160.56  47.2     고장
 92     정상  고부하   경미  35.7  0.539  160.49  47.8     고장
 93     정상  고부하   심각  35.9  0.539  160.91  47.3     고장
 94     정상  고부하   경미  35.9  0.542  160.69  47.4     고장
 95     정상  고부하   심각  36.1  0.551  161.27  47.5     정상
 96     정상  고부하   경미  36.2  0.548  161.08  47.5     정상
 97     정상  고부하   정상  36.3  0.549  161.01  47.3     정상
 98     정상  고부하   심각  36.2  0.547  160.45  47.0     고장
 99     정상  고부하   경미  36.4  0.546  160.22  46.7     고장
 100    정상  고부하   심각  36.4  0.552  160.70  46.3     고장
 101    정상  고부하   경미  36.2  0.550  160.61  46.7     고장
 102    정상  고부하   정상  36.1  0.537  160.96  46.8     정상
 103    정상  고부하   지연  36.2  0.536  161.11  47.2     정상
 104    정상  고부하   정상  36.3  0.530  160.92  47.4     정상
 105    정상  고부하   심각  36.2  0.540  160.48  47.0     고장
 106    정상  고부하   경미  36.3  0.537  160.31  46.8     고장
 107    정상  고부하   정상  36.3  0.541  160.47  46.5     고장
 108    정상  고부하   지연  36.3  0.540  160.64  46.9     고장
 109    정상  고부하   정상  36.2  0.549  160.58  46.8     고장
 110    정상  고부하   지연  36.2  0.544  161.10  47.1     정상
 111    정상  고부하   정상  36.1  0.546  161.00  47.1     정상
 112    정상  고부하   심각  36.0  0.545  160.61  47.5     고장
 113    정상  고부하   지연  35.9  0.550  160.53  46.9     고장
 114    정상  고부하   정상  35.8  0.541  160.41  47.0     고장
 115    정상  고부하   지연  35.7  0.546  160.81  47.0     고장
 116    정상  고부하   정상  35.6  0.544  160.68  46.8     고장
 117    정상  고부하   지연  35.5  0.558  161.32  46.6     정상
 118    정상  고부하   경미  35.4  0.547  161.26  46.6     정상
 119    정상  고부하   정상  35.3  0.547  161.22  46.6     정상)

In [55]:
df.groupby('냉각기상태')['온도']

In [56]:
list(df.groupby('냉각기상태')['온도'])

[('고장',
  0     35.6
  1     47.5
  2     50.7
  3     51.7
  4     52.4
  5     53.1
  6     53.5
  7     53.7
  8     53.9
  9     53.9
  10    54.1
  11    54.3
  12    54.2
  13    54.2
  14    54.5
  15    54.4
  16    54.6
  17    55.0
  18    54.5
  19    54.4
  20    56.0
  21    56.6
  22    56.8
  23    57.1
  24    56.3
  25    56.0
  26    56.0
  27    57.1
  28    57.6
  29    57.5
  30    57.8
  31    57.2
  32    57.0
  33    56.3
  34    57.2
  35    57.2
  36    57.2
  37    57.1
  38    56.6
  39    55.9
  Name: 온도, dtype: float64),
 ('저하',
  40    51.2
  41    48.1
  42    47.4
  43    47.1
  44    46.9
  45    46.8
  46    46.7
  47    46.6
  48    46.5
  49    46.5
  50    46.4
  51    46.1
  52    46.0
  53    46.0
  54    45.9
  55    45.7
  56    45.7
  57    45.6
  58    45.4
  59    45.0
  60    44.8
  61    44.8
  62    44.6
  63    44.6
  64    44.6
  65    44.4
  66    44.1
  67    44.1
  68    44.1
  69    44.1
  70    44.3
  71    44.3
  72    44.3
  73    44.0
  74    44.0
  75    44.1
  76    44.1
  77    44.4
  78    44.5
  79    44.8
  Name: 온도, dtype: float64),
 ('정상',
  80     36.2
  81     35.5
  82     35.4
  83     35.4
  84     35.5
  85     35.5
  86     35.5
  87     35.5
  88     35.4
  89     35.5
  90     35.6
  91     35.7
  92     35.7
  93     35.9
  94     35.9
  95     36.1
  96     36.2
  97     36.3
  98     36.2
  99     36.4
  100    36.4
  101    36.2
  102    36.1
  103    36.2
  104    36.3
  105    36.2
  106    36.3
  107    36.3
  108    36.3
  109    36.2
  110    36.2
  111    36.1
  112    36.0
  113    35.9
  114    35.8
  115    35.7
  116    35.6
  117    35.5
  118    35.4
  119    35.3
  Name: 온도, dtype: float64)]

In [57]:
df.groupby('냉각기상태')['온도'].max()

냉각기상태
고장    57.8
저하    51.2
정상    36.4
Name: 온도, dtype: float64

In [58]:
df.groupby('냉각기상태')['진동'].max()

냉각기상태
고장    0.779
저하    0.629
정상    0.566
Name: 진동, dtype: float64

In [60]:
df.groupby('운전부하')['진동'].max()

운전부하
고부하    0.779
저부하    0.741
Name: 진동, dtype: float64

In [61]:
# 실습4 10시 47분까지

In [64]:
pd.set_option("display.precision", 2)

In [66]:
print(df.groupby("냉각기상태").size().to_dict())
# {'고장': 40, '저하': 40, '정상': 40}      세 그룹이 고르게 나뉨

print(df.groupby("냉각기상태")["온도"].mean().round(2).to_dict())
# {'고장': 54.67, '저하': 45.46, '정상': 35.89}

print(df.groupby("냉각기상태")["온도"].max().to_dict())     # 함수만 갈아 끼움
# {'고장': 57.8, '저하': 51.2, '정상': 36.4}

{'고장': 40, '저하': 40, '정상': 40}
{'고장': 54.67, '저하': 45.46, '정상': 35.89}
{'고장': 57.8, '저하': 51.2, '정상': 36.4}

In [67]:
54.67 - 35.89

18.78

In [68]:
# 여러 기준으로 그룹 묶기

In [69]:
df.columns

Index(['냉각기상태', '운전부하', '밸브상태', '온도', '진동', '압력', '냉각효율', 'result'], dtype='str')

In [70]:
df.groupby(['냉각기상태','운전부하'])

In [71]:
list(df.groupby(['냉각기상태','운전부하']))

[(('고장', '고부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  0     고장  고부하   정상  35.6  0.58  160.67  39.6     정상
  19    고장  고부하   심각  54.4  0.75  173.28  20.2     고장
  20    고장  고부하   경미  56.0  0.78  180.41  20.8     고장
  21    고장  고부하   심각  56.6  0.74  180.70  19.7     고장
  22    고장  고부하   경미  56.8  0.73  172.86  19.0     고장
  25    고장  고부하   정상  56.0  0.73  180.92  20.6     정상
  26    고장  고부하   심각  56.0  0.74  173.03  20.0     고장
  27    고장  고부하   경미  57.1  0.76  173.06  19.3     고장
  28    고장  고부하   심각  57.6  0.72  172.94  18.9     고장
  29    고장  고부하   지연  57.5  0.73  172.87  19.2     고장
  30    고장  고부하   정상  57.8  0.72  172.72  19.2     고장
  31    고장  고부하   지연  57.2  0.77  173.32  19.1     정상
  33    고장  고부하   심각  56.3  0.73  173.06  19.6     고장
  34    고장  고부하   지연  57.2  0.71  166.57  18.8     고장
  35    고장  고부하   정상  57.2  0.72  172.58  18.9     고장
  36    고장  고부하   지연  57.2  0.70  166.75  18.8     고장
  37    고장  고부하   정상  57.1  0.72  172.86  18.7     고장),
 (('고장', '저부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  1     고장  저부하   정상  47.5  0.60  158.65  17.6     정상
  2     고장  저부하   정상  50.7  0.64  157.76  18.7     정상
  3     고장  저부하   정상  51.7  0.64  157.54  19.6     정상
  4     고장  저부하   정상  52.4  0.64  157.36  21.1     정상
  5     고장  저부하   정상  53.1  0.65  157.20  20.9     정상
  6     고장  저부하   정상  53.5  0.67  157.07  20.1     정상
  7     고장  저부하   정상  53.7  0.66  157.09  19.6     정상
  8     고장  저부하   정상  53.9  0.66  156.95  19.6     정상
  9     고장  저부하   정상  53.9  0.67  157.07  19.6     정상
  10    고장  저부하   정상  54.1  0.67  157.00  20.0     정상
  11    고장  저부하   정상  54.3  0.66  157.01  19.9     정상
  12    고장  저부하   지연  54.2  0.66  156.20  19.9     고장
  13    고장  저부하   경미  54.2  0.65  156.14  19.9     고장
  14    고장  저부하   심각  54.5  0.66  156.54  20.1     고장
  15    고장  저부하   경미  54.4  0.66  156.49  20.0     고장
  16    고장  저부하   심각  54.6  0.67  157.07  20.2     정상
  17    고장  저부하   경미  55.0  0.66  156.79  20.6     정상
  18    고장  저부하   정상  54.5  0.68  156.82  20.4     정상
  23    고장  저부하   정상  57.1  0.72  156.08  18.8     정상
  24    고장  저부하   지연  56.3  0.65  156.40  20.3     정상
  32    고장  저부하   정상  57.0  0.74  156.60  19.0     정상
  38    고장  저부하   지연  56.6  0.66  156.31  18.6     정상
  39    고장  저부하   정상  55.9  0.65  156.32  20.1     정상),
 (('저하', '고부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  66    저하  고부하   지연  44.1  0.62  158.45  27.4     고장
  67    저하  고부하   정상  44.1  0.62  158.38  27.3     고장
  73    저하  고부하   지연  44.0  0.61  158.52  27.3     고장),
 (('저하', '저부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  40    저하  저부하   정상  51.2  0.59  157.09  27.0     정상
  41    저하  저부하   정상  48.1  0.59  157.86  26.3     정상
  42    저하  저부하   정상  47.4  0.60  158.09  26.3     정상
  43    저하  저부하   정상  47.1  0.60  158.16  26.3     정상
  44    저하  저부하   정상  46.9  0.59  158.24  26.2     정상
  45    저하  저부하   정상  46.8  0.59  158.25  26.2     정상
  46    저하  저부하   정상  46.7  0.60  158.30  26.4     정상
  47    저하  저부하   정상  46.6  0.60  158.32  26.3     정상
  48    저하  저부하   정상  46.5  0.61  158.30  26.5     정상
  49    저하  저부하   정상  46.5  0.61  158.35  26.8     정상
  50    저하  저부하   정상  46.4  0.62  158.39  26.5     정상
  51    저하  저부하   심각  46.1  0.62  158.10  26.7     고장
  52    저하  저부하   경미  46.0  0.63  157.92  26.9     고장
  53    저하  저부하   정상  46.0  0.62  157.87  27.2     고장
  54    저하  저부하   지연  45.9  0.63  158.30  27.4     고장
  55    저하  저부하   정상  45.7  0.63  158.24  27.7     고장
  56    저하  저부하   지연  45.7  0.62  158.78  28.2     정상
  57    저하  저부하   정상  45.6  0.61  158.64  28.1     정상
  58    저하  저부하   정상  45.4  0.60  158.65  27.8     정상
  59    저하  저부하   지연  45.0  0.61  158.22  27.8     고장
  60    저하  저부하   정상  44.8  0.61  158.12  27.7     고장
  61    저하  저부하   지연  44.8  0.62  158.55  27.5     고장
  62    저하  저부하   정상  44.6  0.61  158.48  27.8     고장
  63    저하  저부하   심각  44.6  0.61  159.12  27.6     정상
  64    저하  저부하   경미  44.6  0.61  158.96  27.6     정상
  65    저하  저부하   정상  44.4  0.60  158.93  27.6     정상
  68    저하  저부하   심각  44.1  0.62  158.85  27.9     고장
  69    저하  저부하   경미  44.1  0.61  158.69  27.5     고장
  70    저하  저부하   심각  44.3  0.61  159.23  27.3     정상
  71    저하  저부하   경미  44.3  0.60  159.05  27.4     정상
  72    저하  저부하   정상  44.3  0.60  158.99  27.5     정상
  74    저하  저부하   경미  44.0  0.62  158.46  27.7     고장
  75    저하  저부하   심각  44.1  0.61  158.85  27.8     고장
  76    저하  저부하   경미  44.1  0.61  158.69  27.2     고장
  77    저하  저부하   심각  44.4  0.61  159.24  27.5     정상
  78    저하  저부하   경미  44.5  0.61  159.07  27.6     정상
  79    저하  저부하   정상  44.8  0.60  158.96  27.9     정상),
 (('정상', '고부하'),
      냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  80     정상  고부하   정상  36.2  0.56  160.72  47.3     정상
  81     정상  고부하   정상  35.5  0.56  160.97  46.5     정상
  82     정상  고부하   정상  35.4  0.57  161.00  46.6     정상
  83     정상  고부하   정상  35.4  0.56  161.04  46.4     정상
  84     정상  고부하   정상  35.5  0.56  161.01  46.7     정상
  85     정상  고부하   정상  35.5  0.56  161.03  46.7     정상
  86     정상  고부하   정상  35.5  0.56  161.03  46.5     정상
  87     정상  고부하   정상  35.5  0.56  161.04  46.7     정상
  88     정상  고부하   정상  35.4  0.55  161.04  46.9     정상
  89     정상  고부하   정상  35.5  0.56  161.04  47.2     정상
  90     정상  고부하   정상  35.6  0.55  161.16  47.4     정상
  91     정상  고부하   지연  35.7  0.55  160.56  47.2     고장
  92     정상  고부하   경미  35.7  0.54  160.49  47.8     고장
  93     정상  고부하   심각  35.9  0.54  160.91  47.3     고장
  94     정상  고부하   경미  35.9  0.54  160.69  47.4     고장
  95     정상  고부하   심각  36.1  0.55  161.27  47.5     정상
  96     정상  고부하   경미  36.2  0.55  161.08  47.5     정상
  97     정상  고부하   정상  36.3  0.55  161.01  47.3     정상
  98     정상  고부하   심각  36.2  0.55  160.45  47.0     고장
  99     정상  고부하   경미  36.4  0.55  160.22  46.7     고장
  100    정상  고부하   심각  36.4  0.55  160.70  46.3     고장
  101    정상  고부하   경미  36.2  0.55  160.61  46.7     고장
  102    정상  고부하   정상  36.1  0.54  160.96  46.8     정상
  103    정상  고부하   지연  36.2  0.54  161.11  47.2     정상
  104    정상  고부하   정상  36.3  0.53  160.92  47.4     정상
  105    정상  고부하   심각  36.2  0.54  160.48  47.0     고장
  106    정상  고부하   경미  36.3  0.54  160.31  46.8     고장
  107    정상  고부하   정상  36.3  0.54  160.47  46.5     고장
  108    정상  고부하   지연  36.3  0.54  160.64  46.9     고장
  109    정상  고부하   정상  36.2  0.55  160.58  46.8     고장
  110    정상  고부하   지연  36.2  0.54  161.10  47.1     정상
  111    정상  고부하   정상  36.1  0.55  161.00  47.1     정상
  112    정상  고부하   심각  36.0  0.55  160.61  47.5     고장
  113    정상  고부하   지연  35.9  0.55  160.53  46.9     고장
  114    정상  고부하   정상  35.8  0.54  160.41  47.0     고장
  115    정상  고부하   지연  35.7  0.55  160.81  47.0     고장
  116    정상  고부하   정상  35.6  0.54  160.68  46.8     고장
  117    정상  고부하   지연  35.5  0.56  161.32  46.6     정상
  118    정상  고부하   경미  35.4  0.55  161.26  46.6     정상
  119    정상  고부하   정상  35.3  0.55  161.22  46.6     정상)]

In [72]:
list(df.groupby(['냉각기상태','운전부하']))[0]

(('고장', '고부하'),
    냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
 0     고장  고부하   정상  35.6  0.58  160.67  39.6     정상
 19    고장  고부하   심각  54.4  0.75  173.28  20.2     고장
 20    고장  고부하   경미  56.0  0.78  180.41  20.8     고장
 21    고장  고부하   심각  56.6  0.74  180.70  19.7     고장
 22    고장  고부하   경미  56.8  0.73  172.86  19.0     고장
 25    고장  고부하   정상  56.0  0.73  180.92  20.6     정상
 26    고장  고부하   심각  56.0  0.74  173.03  20.0     고장
 27    고장  고부하   경미  57.1  0.76  173.06  19.3     고장
 28    고장  고부하   심각  57.6  0.72  172.94  18.9     고장
 29    고장  고부하   지연  57.5  0.73  172.87  19.2     고장
 30    고장  고부하   정상  57.8  0.72  172.72  19.2     고장
 31    고장  고부하   지연  57.2  0.77  173.32  19.1     정상
 33    고장  고부하   심각  56.3  0.73  173.06  19.6     고장
 34    고장  고부하   지연  57.2  0.71  166.57  18.8     고장
 35    고장  고부하   정상  57.2  0.72  172.58  18.9     고장
 36    고장  고부하   지연  57.2  0.70  166.75  18.8     고장
 37    고장  고부하   정상  57.1  0.72  172.86  18.7     고장)

In [73]:
df.groupby(["냉각기상태", "운전부하"])["온도"].mean()

냉각기상태  운전부하
고장     고부하     55.51
       저부하     54.05
저하     고부하     44.07
       저부하     45.58
정상     고부하     35.89
Name: 온도, dtype: float64

In [74]:
print(df.groupby(["냉각기상태", "운전부하"])["온도"].mean())

냉각기상태  운전부하
고장     고부하     55.51
       저부하     54.05
저하     고부하     44.07
       저부하     45.58
정상     고부하     35.89
Name: 온도, dtype: float64

In [76]:
pd.crosstab(df['냉각기상태'], df['운전부하'])

운전부하   고부하  저부하
냉각기상태
고장      17   23
저하       3   37
정상      40    0

In [77]:
pd.crosstab(df['밸브상태'],df['result'])

result  고장  정상
밸브상태
경미      14   6
심각      14   5
정상      12  49
지연      13   7

In [78]:
pd.crosstab(df['밸브상태'],df['result'], normalize='index')

result    고장    정상
밸브상태
경미      0.70  0.30
심각      0.74  0.26
정상      0.20  0.80
지연      0.65  0.35

In [79]:
pd.crosstab(df['밸브상태'],df['result'], normalize='columns')

result    고장    정상
밸브상태
경미      0.26  0.09
심각      0.26  0.07
정상      0.23  0.73
지연      0.25  0.10

In [80]:
df.groupby(['냉각기상태','운전부하'])['온도']

In [81]:
df.groupby(['냉각기상태','운전부하'])['온도'].mean()

냉각기상태  운전부하
고장     고부하     55.51
       저부하     54.05
저하     고부하     44.07
       저부하     45.58
정상     고부하     35.89
Name: 온도, dtype: float64

In [82]:
df.groupby(['냉각기상태','운전부하'])['온도'].mean().unstack()

운전부하     고부하    저부하
냉각기상태
고장     55.51  54.05
저하     44.07  45.58
정상     35.89    NaN

In [85]:
# 실습5 11시 35분까지 전체

In [84]:
# 제출

In [86]:
# 주석 다는 연습과 깃에 올리기 연습

In [87]:
df.groupby('냉각기상태')['온도']

In [88]:
df.groupby('냉각기상태')['온도'].agg('mean')

냉각기상태
고장    54.67
저하    45.46
정상    35.89
Name: 온도, dtype: float64

In [89]:
df.groupby('냉각기상태')['온도'].agg(['mean','std','max'])

        mean   std   max
냉각기상태
고장     54.67  3.76  57.8
저하     45.46  1.47  51.2
정상     35.89  0.36  36.4

In [91]:
df.groupby('냉각기상태').agg(
    평균온도 =('온도', 'mean'),
온도편차 =('온도', 'std'),
평균진동 =('진동', 'mean'),
측정수 =('온도', 'count'),
)

        평균온도  온도편차  평균진동  측정수
냉각기상태
고장     54.67  3.76  0.69   40
저하     45.46  1.47  0.61   40
정상     35.89  0.36  0.55   40

In [92]:
# 실습1 2시 25분까지

In [93]:
qc.head()

  검사결과    온도    진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0   합격  44.7  0.61  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1   합격  41.9  0.61  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2   합격  40.1  0.60  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3   합격  38.9  0.59  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4   합격  38.0  0.58  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0

In [94]:
qc.groupby("검사결과").agg(평균온도=("온도", "mean"),
    평균냉각효율=("냉각효율", "mean"),
    측정수=("온도", "count"))

       평균온도  평균냉각효율  측정수
검사결과
불합격   55.84   19.65   12
합격    35.91   46.88  188

In [95]:
# 구분        mean                 transform('mean')
# 결과 줄 수   그룹 수만큼 (3줄)      원래 행 수만큼 (120줄)
# 쓰임        그룹끼리 비교하는 표    원본에 새 열로 붙이기
# 이어서 할 일 정렬해서 우선순위      내 값이 그룹 평균에서 얼마나 떨어졌나

In [96]:
df.groupby('냉각기상태')['온도'].mean()

냉각기상태
고장    54.67
저하    45.46
정상    35.89
Name: 온도, dtype: float64

In [97]:
df.groupby('냉각기상태')['온도'].transform('mean')

0      54.67
1      54.67
2      54.67
3      54.67
4      54.67
       ...
115    35.89
116    35.89
117    35.89
118    35.89
119    35.89
Name: 온도, Length: 120, dtype: float64

In [98]:
marked=df.copy()

In [99]:
marked.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상

In [100]:
marked['그룹평균']=marked.groupby('냉각기상태')['온도'].transform('mean')

In [101]:
marked

    냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result   그룹평균
0      고장  고부하   정상  35.6  0.58  160.67  39.6     정상  54.67
1      고장  저부하   정상  47.5  0.60  158.65  17.6     정상  54.67
2      고장  저부하   정상  50.7  0.64  157.76  18.7     정상  54.67
3      고장  저부하   정상  51.7  0.64  157.54  19.6     정상  54.67
4      고장  저부하   정상  52.4  0.64  157.36  21.1     정상  54.67
..    ...  ...  ...   ...   ...     ...   ...    ...    ...
115    정상  고부하   지연  35.7  0.55  160.81  47.0     고장  35.89
116    정상  고부하   정상  35.6  0.54  160.68  46.8     고장  35.89
117    정상  고부하   지연  35.5  0.56  161.32  46.6     정상  35.89
118    정상  고부하   경미  35.4  0.55  161.26  46.6     정상  35.89
119    정상  고부하   정상  35.3  0.55  161.22  46.6     정상  35.89

[120 rows x 9 columns]

In [104]:
marked['온도'] - marked['그룹평균']

0     -19.07
1      -7.17
2      -3.97
3      -2.97
4      -2.27
       ...
115    -0.19
116    -0.29
117    -0.39
118    -0.49
119    -0.59
Length: 120, dtype: float64

In [105]:
marked['편차'] = marked['온도'] - marked['그룹평균']

In [106]:
marked.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result   그룹평균     편차
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상  54.67 -19.07
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상  54.67  -7.17
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상  54.67  -3.97
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상  54.67  -2.97
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상  54.67  -2.27

In [110]:
marked.groupby('냉각기상태')['편차'].sum().round(4)

냉각기상태
고장    0.0
저하    0.0
정상   -0.0
Name: 편차, dtype: float64

In [111]:
marked = df.copy()
marked["그룹평균"] = marked.groupby("냉각기상태")["온도"].transform("mean").round(2)
marked["편차"] = (marked["온도"] - marked["그룹평균"]).round(2)
print(marked[["냉각기상태", "온도", "그룹평균", "편차"]].head(3).to_string(index=False))

냉각기상태   온도  그룹평균     편차
   고장 35.6 54.67 -19.07
   고장 47.5 54.67  -7.17
   고장 50.7 54.67  -3.97

In [112]:
print(marked.groupby("냉각기상태")["편차"].sum().round(2).to_dict())

{'고장': -0.1, '저하': 0.2, '정상': -0.2}

In [113]:
df.columns

Index(['냉각기상태', '운전부하', '밸브상태', '온도', '진동', '압력', '냉각효율', 'result'], dtype='str')

In [115]:
pd.pivot_table(df, index='밸브상태', columns='운전부하',
values='온도', aggfunc='mean')

운전부하    고부하    저부하
밸브상태
경미    42.20  47.52
심각    45.25  47.09
정상    39.34  49.40
지연    43.75  49.79

In [118]:
# 3시에 실습2, 3시 15분까지

In [117]:
# 제출

In [119]:
marked = df.copy()

In [120]:
marked["그룹평균"] = marked.groupby("냉각기상태")["온도"].transform("mean").round(2)

In [121]:
marked["편차"] = (marked["온도"] - marked["그룹평균"]).round(2)

In [122]:
print(marked[["냉각기상태", "온도", "그룹평균", "편차"]].head(3))

  냉각기상태    온도   그룹평균     편차
0    고장  35.6  54.67 -19.07
1    고장  47.5  54.67  -7.17
2    고장  50.7  54.67  -3.97

In [123]:
marked["거리"] = marked["편차"].abs()

In [124]:
marked.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result   그룹평균     편차     거리
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상  54.67 -19.07  19.07
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상  54.67  -7.17   7.17
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상  54.67  -3.97   3.97
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상  54.67  -2.97   2.97
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상  54.67  -2.27   2.27

In [125]:
print(marked.sort_values("거리", ascending=False).head(1)[
      ["냉각기상태", "온도", "그룹평균", "편차"]])

  냉각기상태    온도   그룹평균     편차
0    고장  35.6  54.67 -19.07

In [126]:
print(pd.pivot_table(marked, index="밸브상태", columns="운전부하", values="온도",
                     aggfunc="mean", margins=True, margins_name="전체"))

운전부하    고부하    저부하     전체
밸브상태
경미    42.20  47.52  44.86
심각    45.25  47.09  46.02
정상    39.34  49.40  45.11
지연    43.75  49.79  45.86
전체    41.85  48.83  45.34

In [127]:
print(round(df["온도"].corr(df["진동"]), 3))       #  0.931
print(round(df["온도"].corr(df["압력"]), 3))       #  0.284
print(round(df["온도"].corr(df["냉각효율"]), 3))   # -0.951

0.931
0.284
-0.951

In [128]:
# 실습3 3시 25분까지

In [129]:
print(round(df["온도"].corr(df["진동"]), 3))       #  0.931
print(round(df["온도"].corr(df["압력"]), 3))       #  0.284
print(round(df["온도"].corr(df["냉각효율"]), 3))   # -0.951

four = df[["온도", "진동", "압력", "냉각효율"]]
print(four.corr().round(3).to_string())

0.931
0.284
-0.951
        온도    진동    압력  냉각효율
온도    1.00  0.93  0.28 -0.95
진동    0.93  1.00  0.52 -0.86
압력    0.28  0.52  1.00 -0.13
냉각효율 -0.95 -0.86 -0.13  1.00

In [131]:
# 실습4 4시 20분까지

In [132]:
qc.head()

  검사결과    온도    진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0   합격  44.7  0.61  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1   합격  41.9  0.61  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2   합격  40.1  0.60  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3   합격  38.9  0.59  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4   합격  38.0  0.58  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0

In [ ]:
qc.columns

    검사결과    온도    진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0     합격  44.7  0.61  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1     합격  41.9  0.61  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2     합격  40.1  0.60  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3     합격  38.9  0.59  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4     합격  38.0  0.58  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0
..   ...   ...   ...     ...   ...   ...     ...   ...     ...   ...   ...
195  불합격  57.0  0.73  172.68  18.8  3.29  2633.0  30.3  122.84  1.08  60.6
196  불합격  57.5  0.71  172.51  18.9  3.29  2626.9  30.4  122.94  1.07  60.8
197  불합격  56.6  0.74  172.92  18.9  3.22  2626.6  29.1  122.47  1.09  59.9
198  불합격  57.1  0.80  172.78  19.0  3.29  2624.0  29.5  122.56  1.11  60.4
199  불합격  57.2  0.73  172.56  18.9  3.26  2621.5  30.2  122.95  1.10  60.7

[200 rows x 11 columns]

In [143]:
qc.drop(columns=['검사결과'])

       온도    진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0    44.7  0.61  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1    41.9  0.61  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2    40.1  0.60  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3    38.9  0.59  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4    38.0  0.58  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0
..    ...   ...     ...   ...   ...     ...   ...     ...   ...   ...
195  57.0  0.73  172.68  18.8  3.29  2633.0  30.3  122.84  1.08  60.6
196  57.5  0.71  172.51  18.9  3.29  2626.9  30.4  122.94  1.07  60.8
197  56.6  0.74  172.92  18.9  3.22  2626.6  29.1  122.47  1.09  59.9
198  57.1  0.80  172.78  19.0  3.29  2624.0  29.5  122.56  1.11  60.4
199  57.2  0.73  172.56  18.9  3.26  2621.5  30.2  122.95  1.10  60.7

[200 rows x 10 columns]

In [144]:
qc_new=qc.drop(columns=['검사결과'])

In [146]:
qc_new.shape

(200, 10)

In [147]:
qc_new.corr().shape

(10, 10)

In [145]:
qc_new.corr()

        온도    진동    압력  냉각효율    유량  모터전력  효율지수  보조압력  냉각출력  배유온도
온도    1.00  0.94  0.72 -0.98 -0.90  0.33 -0.88  0.76 -0.96  1.00
진동    0.94  1.00  0.80 -0.94 -0.93  0.48 -0.92  0.84 -0.96  0.94
압력    0.72  0.80  1.00 -0.71 -0.95  0.89 -0.96  0.99 -0.88  0.70
냉각효율 -0.98 -0.94 -0.71  1.00  0.89 -0.33  0.87 -0.75  0.95 -0.98
유량   -0.90 -0.93 -0.95  0.89  1.00 -0.71  1.00 -0.97  0.98 -0.88
모터전력  0.33  0.48  0.89 -0.33 -0.71  1.00 -0.73  0.85 -0.57  0.30
효율지수 -0.88 -0.92 -0.96  0.87  1.00 -0.73  1.00 -0.97  0.98 -0.87
보조압력  0.76  0.84  0.99 -0.75 -0.97  0.85 -0.97  1.00 -0.91  0.74
냉각출력 -0.96 -0.96 -0.88  0.95  0.98 -0.57  0.98 -0.91  1.00 -0.95
배유온도  1.00  0.94  0.70 -0.98 -0.88  0.30 -0.87  0.74 -0.95  1.00

In [148]:
len(qc.columns)

11

In [ ]:
# 칼럼갯수

In [149]:
# 자기자신(1)을 뺀
11 - 1

10

In [151]:
# 대각선을 뺀 짝의 갯수

In [150]:
(10 * 9) / 2

45.0

In [152]:
qc_new_half=qc_new.corr()

In [158]:
qc_new_half.abs() >= 0.4

         온도    진동    압력   냉각효율    유량   모터전력  효율지수  보조압력  냉각출력   배유온도
온도     True  True  True   True  True  False  True  True  True   True
진동     True  True  True   True  True   True  True  True  True   True
압력     True  True  True   True  True   True  True  True  True   True
냉각효율   True  True  True   True  True  False  True  True  True   True
유량     True  True  True   True  True   True  True  True  True   True
모터전력  False  True  True  False  True   True  True  True  True  False
효율지수   True  True  True   True  True   True  True  True  True   True
보조압력   True  True  True   True  True   True  True  True  True   True
냉각출력   True  True  True   True  True   True  True  True  True   True
배유온도   True  True  True   True  True  False  True  True  True   True

In [159]:
qc_new_half[qc_new_half.abs() >= 0.4]

        온도    진동    압력  냉각효율    유량  모터전력  효율지수  보조압력  냉각출력  배유온도
온도    1.00  0.94  0.72 -0.98 -0.90   NaN -0.88  0.76 -0.96  1.00
진동    0.94  1.00  0.80 -0.94 -0.93  0.48 -0.92  0.84 -0.96  0.94
압력    0.72  0.80  1.00 -0.71 -0.95  0.89 -0.96  0.99 -0.88  0.70
냉각효율 -0.98 -0.94 -0.71  1.00  0.89   NaN  0.87 -0.75  0.95 -0.98
유량   -0.90 -0.93 -0.95  0.89  1.00 -0.71  1.00 -0.97  0.98 -0.88
모터전력   NaN  0.48  0.89   NaN -0.71  1.00 -0.73  0.85 -0.57   NaN
효율지수 -0.88 -0.92 -0.96  0.87  1.00 -0.73  1.00 -0.97  0.98 -0.87
보조압력  0.76  0.84  0.99 -0.75 -0.97  0.85 -0.97  1.00 -0.91  0.74
냉각출력 -0.96 -0.96 -0.88  0.95  0.98 -0.57  0.98 -0.91  1.00 -0.95
배유온도  1.00  0.94  0.70 -0.98 -0.88   NaN -0.87  0.74 -0.95  1.00

In [160]:
qc_new_half[qc_new_half.abs() >= 0.4].notna().sum()

온도       9
진동      10
압력      10
냉각효율     9
유량      10
모터전력     7
효율지수    10
보조압력    10
냉각출력    10
배유온도     9
dtype: int64

In [161]:
qc_new_half[qc_new_half.abs() >= 0.4].notna().sum().sum()

np.int64(94)

In [ ]:
qc_new_half[qc_new_half.abs() >= 0.4].notna().sum()

np.float64(42.0)

In [163]:
qc_new_half[qc_new_half.abs() >= 0.95].notna().sum()

온도      4
진동      2
압력      4
냉각효율    3
유량      5
모터전력    1
효율지수    5
보조압력    4
냉각출력    6
배유온도    4
dtype: int64

In [164]:
qc_new_half[qc_new_half.abs() >= 0.95].notna().sum().sum()

np.int64(38)

In [165]:
(38 - 10) / 2

14.0

In [166]:
# 종합 실습 4시 50분