In [2]:
import pandas as pd

In [4]:
log=pd.read_csv('..//data//13_diecasting_shot.csv')

In [5]:
master=pd.read_csv('..//data//13_diecasting_master.csv')

In [6]:
log.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [7]:
log.to_string()

'       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급\n0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품\n1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품\n2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품\n3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품\n4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품\n5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품\n6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품\n7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품\n8      9  DIE-B-02  215.0  1039.0    20.9   11.0  258.0   양품\n9     10  DIE-A-01  218.0  1053.0    20.8   12.0  257.0   양품\n10    11  DIE-B-01  218.0  1054.0    21.0   11.0  258.0   양품\n11    12  DIE-A-01  214.0  1038.0    20.8   11.0  257.0   양품\n12    13  DIE-A-02  214.0  1037.0    20.8   11.0  257.0   양품\n13    14  DIE-A-02  218.0  1053.0    20.9   11.0  257.0   양품\n14    15  DIE-B-02  214.0  1037.0    20.8   12.0  255.0   양품\n15    16  DIE-B-01  218.0  1055.0    20.9   11.0  255.0   양품\n16    17  DIE-A-01  217.0  1051.0    20.9   12.0  257.0   양품\n17    18  DIE-A-02  218.0  1055.0    20.7   11.0  255.0   양품\n18    19  DIE-A-01  217.0  1051.0    20.9   11.0  257.0   양품\n19    20  DIE-B-02  214.0  1037.0    20.8   12.0  257.0   양품\n20    21  DIE-B-02  217.0  1052.0    20.9   12.0  257.0   양품\n21    22  DIE-B-02  214.0  1038.0    20.7   12.0  255.0   양품\n22    23  DIE-B-02  216.0  1046.0    20.8   11.0  257.0   양품\n23    24  DIE-B-02  214.0  1038.0    20.7   12.0  257.0   양품\n24    25  DIE-C-01  214.0  1037.0    20.7   11.0  257.0   양품\n25    26  DIE-B-02  218.0  1053.0    20.8   11.0  257.0   양품\n26    27  DIE-A-01  215.0  1039.0    20.8   11.0  257.0   양품\n27    28  DIE-B-02  218.0  1054.0    20.8   12.0  254.0   양품\n28    29  DIE-A-02  215.0  1040.0    20.9   12.0  258.0   양품\n29    30  DIE-B-02  214.0  1037.0    20.8   12.0  258.0   양품\n30    31  DIE-B-01  218.0  1055.0    20.8   12.0  258.0   양품\n31    32  DIE-A-02  214.0  1037.0    20.9   13.0  258.0   양품\n32    33  DIE-A-02  218.0  1055.0    20.8   12.0  257.0   양품\n33    34  DIE-A-02  215.0  1038.0    20.9   12.0  257.0   양품\n34    35  DIE-A-02  215.0  1040.0    20.9   12.0  257.0   양품\n35    36  DIE-A-01  217.0  1052.0    20.8   11.0  255.0   양품\n36    37  DIE-B-02  218.0  1055.0    20.9   12.0  257.0   양품\n37    38  DIE-B-02  218.0  1053.0    20.8   12.0  258.0   양품\n38    39  DIE-C-01  215.0  1040.0    20.9   11.0  257.0   양품\n39    40  DIE-B-01  218.0  1053.0    20.8   11.0  255.0   양품\n40    41  DIE-B-01  218.0  1055.0    21.0   11.0  257.0   양품\n41    42  DIE-B-02  215.0  1040.0    20.9   11.0  254.0   양품\n42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의\n43    44  DIE-B-01  214.0  1036.0    21.0   10.0  259.0   양품\n44    45  DIE-A-02  214.0  1037.0    20.7   11.0  251.0   양품\n45    46  DIE-A-01  217.0  1052.0    20.7   11.0  261.0   양품\n46    47  DIE-A-01  214.0  1036.0    20.7   11.0  257.0   양품\n47    48  DIE-B-01  214.0  1036.0    20.7   11.0  253.0   양품\n48    49  DIE-A-01  217.0  1052.0    20.8   12.0  255.0   양품\n49    50  DIE-A-02  214.0  1038.0    20.7   11.0  259.0   양품\n50    51  DIE-B-01  217.0  1051.0    20.8   11.0  258.0   양품\n51    52  DIE-A-02  214.0  1036.0    20.8   11.0  257.0   양품\n52    53  DIE-A-01  217.0  1051.0    20.7   11.0  258.0   양품\n53    54  DIE-A-02  217.0  1051.0    20.7   11.0  255.0   양품\n54    55  DIE-A-01  218.0  1053.0    20.7   11.0  255.0   양품\n55    56  DIE-A-01  217.0  1052.0    20.7   11.0  257.0   양품\n56    57  DIE-A-01  217.0  1052.0    20.7   11.0  258.0   양품\n57    58  DIE-A-02  214.0  1037.0    20.8   11.0  258.0   양품\n58    59  DIE-A-01  218.0  1053.0    20.8   11.0  253.0   양품\n59    60  DIE-B-01  218.0  1053.0    20.7   11.0  253.0   양품\n60    61  DIE-C-01  214.0  1037.0    20.6   11.0  254.0   양품\n61    62  DIE-A-02  216.0  1048.0    20.8   11.0  254.0   양품\n62    63  DIE-B-02  218.0  1053.0    20.6   12.0  254.0   양품\n63    64  DIE-C-01  215.0  1040.0    20.6   11.0  254.0   양품\n64    65  DIE-A-01  218.0  1054.0    20.7   12.0  253.0   양품\n65    66  DIE-A-01  214.0  1038.0    20.7   10.0  253.0   양품\n66    67  DIE-B-02  218.0  1054.0    21.2   12.0  257.0   양품\n67    68  DIE-B-02  215.0  1040.0    21.1   17.0  257.0   양품\n68    69  DIE-B-01  218.0  1054.0    21.2   12.0  254.0   양품\n69    70  DIE-A-01  214.0  1038.0    21.0   11.0  254.0   양품\n70    71  DIE-A-02  214.0  1038.0    21.2   12.0  254.0   양품\n71    72  DIE-B-02  214.0  1038.0    21.1   12.0  253.0   양품\n72    73  DIE-C-01  218.0  1057.0    21.2   13.0  257.0   양품\n73    74  DIE-B-02  218.0  1055.0    21.3   12.0  258.0   양품\n74    75  DIE-A-01  215.0  1041.0    21.2   13.0  258.0   양품\n75    76  DIE-B-02  218.0  1055.0    21.1   13.0  259.0   양품\n76    77  DIE-A-02  218.0  1057.0    21.0   13.0  259.0   양품\n77    78  DIE-B-02  215.0  1041.0    21.0   12.0  253.0   양품\n78    79  DIE-A-01  218.0  1057.0    21.4   13.0  257.0   양품\n79    80  DIE-C-01  218.0  1054.0    21.3   14.0  253.0   양품\n80    81  DIE-B-01  218.0  1057.0    21.2   14.0  255.0   양품\n81    82  DIE-B-02  218.0  1056.0    21.3   13.0  255.0   양품\n82    83  DIE-A-01  216.0  1045.0    21.5   12.0  258.0   양품\n83    84  DIE-B-01  214.0  1038.0    21.2   12.0  258.0   양품\n84    85  DIE-B-01  239.0  1156.0    22.6   12.0  255.0   양품\n85    86  DIE-B-01  235.0  1135.0    22.6   11.0  254.0   양품\n86    87  DIE-A-02  239.0  1154.0    22.6   10.0  258.0   양품\n87    88  DIE-B-02  239.0  1157.0    22.7   11.0  253.0   양품\n88    89  DIE-A-02  235.0  1137.0    22.7   13.0  261.0   양품\n89    90  DIE-A-02  235.0  1137.0    22.5    7.0  255.0   주의\n90    91  DIE-A-01  239.0  1155.0    22.7   13.0  259.0   양품\n91    92  DIE-B-01  239.0  1155.0    22.5   13.0  250.0   양품\n92    93  DIE-A-01  235.0  1136.0    22.7   14.0  255.0   양품\n93    94  DIE-A-01  239.0  1158.0    22.8   15.0  257.0   양품\n94    95  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품\n95    96  DIE-B-01    NaN     NaN     NaN    NaN    NaN   양품\n96    97  DIE-B-01    NaN     NaN     NaN    NaN    NaN   양품\n97    98  DIE-B-01    NaN     NaN     NaN    NaN    NaN   양품\n98    99  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품\n99   100  DIE-A-02    NaN     NaN     NaN    NaN    NaN   양품\n100  101  DIE-A-02    NaN     NaN     NaN    NaN    NaN   양품\n101  102  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품\n102  103  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품\n103  104  DIE-C-01    NaN     NaN     NaN    NaN    NaN   양품\n104  105  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품\n105  106  DIE-A-02  239.0  1159.0    22.7   14.0  254.0   양품\n106  107  DIE-A-02  239.0  1155.0    20.7   13.0  254.0   양품\n107  108  DIE-B-01  239.0  1157.0    23.7   13.0  253.0   양품\n108  109  DIE-A-01  264.0   594.0    36.4   18.0  363.0   양품\n109  110  DIE-A-02  265.0   596.0    36.6   17.0  352.0   양품\n110  111  DIE-A-02  264.0   595.0    37.0   18.0  361.0   양품\n111  112  DIE-B-02  265.0   595.0    36.9   17.0  355.0   양품\n112  113  DIE-A-01  264.0   594.0    33.9   16.0  363.0   양품\n113  114  DIE-A-02  264.0   594.0    34.0   13.0  355.0   양품\n114  115  DIE-A-02  265.0   596.0    34.1   16.0  357.0   양품\n115  116  DIE-C-01  265.0   595.0    34.0   17.0  355.0   양품\n116  117  DIE-B-01  264.0   595.0    34.0   17.0  355.0   양품\n117  118  DIE-A-02  264.0   595.0    33.9   16.0  355.0   양품\n118  119  DIE-B-01  264.0   595.0    33.9   17.0  357.0   양품\n119  120  DIE-A-02  264.0   594.0    33.9   18.0  357.0   양품\n120  121  DIE-A-01  265.0   596.0    33.9   19.0  354.0   주의\n121  122  DIE-B-01  264.0   595.0    33.7   15.0  364.0   양품\n122  123  DIE-C-01  265.0   596.0    33.7   19.0  357.0   주의\n123  124  DIE-B-02  265.0   595.0    33.9   19.0  359.0   주의\n124  125  DIE-A-01  265.0   595.0    33.8   19.0  355.0   주의\n125  126  DIE-B-01  264.0   595.0    33.8   18.0  350.0   양품\n126  127  DIE-B-02  263.0   591.0    33.9   13.0  361.0   양품\n127  128  DIE-A-01  265.0   595.0    34.0   17.0  366.0   양품\n128  129  DIE-B-01  263.0   592.0    34.0   18.0  363.0   양품\n129  130  DIE-A-02  265.0   596.0    33.9   16.0  368.0   양품\n130  131  DIE-A-01  265.0   596.0    34.0   14.0  361.0   양품\n131  132  DIE-A-02  265.0   596.0    33.9   15.0  372.0   양품\n132  133  DIE-A-01  265.0   596.0    35.0   19.0  373.0   주의\n133  134  DIE-A-02  263.0   593.0    36.2   15.0  372.0   양품\n134  135  DIE-A-01  265.0   597.0    36.1   18.0  372.0   양품\n135  136  DIE-A-02  265.0   595.0    36.0   19.0  377.0   주의\n136  137  DIE-A-01  265.0   596.0    36.0   17.0  375.0   양품\n137  138  DIE-B-02  265.0   595.0    35.9   17.0  375.0   양품\n138  139  DIE-B-01  265.0   596.0    36.0   17.0  377.0   양품\n139  140  DIE-A-01  265.0   595.0    36.0   15.0  377.0   양품\n140  141  DIE-B-02  265.0   596.0    36.0   16.0  377.0   양품\n141  142  DIE-A-01  265.0   596.0    35.9   17.0  381.0   양품\n142  143  DIE-A-02  265.0   595.0    36.0   17.0  381.0   양품\n143  144  DIE-B-01  265.0   596.0    36.0   18.0  377.0   양품\n144  145  DIE-A-02  265.0   596.0    36.1   13.0  377.0   양품\n145  146  DIE-A-02  265.0   597.0    36.0   17.0  377.0   양품\n146  147  DIE-A-02  263.0   592.0   125.9   19.0  372.0   주의\n147  148  DIE-A-01  265.0   596.0    36.0   17.0  375.0   양품\n148  149  DIE-B-02  265.0   596.0    36.0   19.0  377.0   주의\n149  150  DIE-A-01  265.0   596.0    36.1   19.0  350.0   주의\n150  151  DIE-B-02  265.0   596.0    36.0   17.0  373.0   양품\n151  152  DIE-A-01  265.0   595.0    35.9   19.0  381.0   주의\n152  153  DIE-A-02  265.0   595.0    36.0   19.0  352.0   주의\n153  154  DIE-A-02  265.0   596.0    36.0   18.0  363.0   양품\n154  155  DIE-A-01  265.0   595.0    35.8   19.0  363.0   주의\n155  156  DIE-A-01  265.0   596.0    35.7   19.0  364.0   주의\n156  157  DIE-A-02  265.0   595.0    35.9   16.0  352.0   양품\n157  158  DIE-A-02  264.0   594.0    35.6   16.0  373.0   양품\n158  159  DIE-B-02  265.0   597.0    35.8   16.0  377.0   양품\n159  160  DIE-C-01  264.0   595.0    35.8   18.0  381.0   양품\n160  161  DIE-A-01  265.0   595.0    35.8   18.0  381.0   양품\n161  162  DIE-B-01  265.0   596.0    36.0   17.0  381.0   양품\n162  163  DIE-A-01  264.0   595.0    36.0   17.0  382.0   양품\n163  164  DIE-B-02  265.0   595.0    35.8   19.0  379.0   주의\n164  165  DIE-A-02  265.0   596.0    35.8   18.0  379.0   양품\n165  166  DIE-C-01  265.0   596.0    35.7   18.0  379.0   양품\n166  167  DIE-B-01  264.0   595.0    35.9   18.0  382.0   양품\n167  168  DIE-A-01  265.0   596.0    36.0   19.0  379.0   주의\n168  169  DIE-A-01  265.0   596.0    36.1   18.0  382.0   양품\n169  170  DIE-A-01  265.0   596.0    36.1   18.0  382.0   양품\n170  171  DIE-B-02  265.0   596.0    36.1   20.0  370.0   주의\n171  172  DIE-A-01  265.0   595.0    36.1   17.0  384.0   양품\n172  173  DIE-A-02  265.0   595.0    36.1   17.0  366.0   양품\n173  174  DIE-A-02  265.0   596.0    36.1   17.0  357.0   양품\n174  175  DIE-A-02  265.0   595.0    36.0   18.0  357.0   양품\n175  176  DIE-B-02  265.0   596.0    36.0   17.0  359.0   양품\n176  177  DIE-A-01  264.0   595.0    36.0   17.0  361.0   양품\n177  178  DIE-B-02  264.0   595.0    36.0   17.0  355.0   양품\n178  179  DIE-B-01  265.0   595.0    36.1   16.0  372.0   양품\n179  180  DIE-C-01  265.0   596.0    36.2   18.0  382.0   양품\n180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량\n181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량\n182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량\n183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량\n184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량\n185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량\n186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량\n187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량\n188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량\n189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량\n190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량\n191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량\n192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량\n193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량\n194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량\n195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량\n196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량\n197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량\n198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량\n199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량'

In [9]:
log.head(3)[['샷','설비ID','비스킷두께']]

   샷      설비ID  비스킷두께
0  1  DIE-A-01   10.0
1  2  DIE-B-01   11.0
2  3  DIE-B-01   11.0

In [10]:
three=log.head(3)[['샷','설비ID','비스킷두께']]

In [11]:
three

   샷      설비ID  비스킷두께
0  1  DIE-A-01   10.0
1  2  DIE-B-01   11.0
2  3  DIE-B-01   11.0

In [12]:
three.to_string(index=False)

' 샷     설비ID  비스킷두께\n 1 DIE-A-01   10.0\n 2 DIE-B-01   11.0\n 3 DIE-B-01   11.0'

In [13]:
print(three.to_string(index=False))

 샷     설비ID  비스킷두께
 1 DIE-A-01   10.0
 2 DIE-B-01   11.0
 3 DIE-B-01   11.0

In [14]:
print(three.to_string(index=True))

   샷      설비ID  비스킷두께
0  1  DIE-A-01   10.0
1  2  DIE-B-01   11.0
2  3  DIE-B-01   11.0

In [15]:
pd.merge(master,log)

,설비ID,라인,도입연도,정격형체력,담당반,샷,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급
0,DIE-A-01,A,2018,280,1반,1,214.0,1037.0,20.7,10.0,258.0,양품
1,DIE-A-01,A,2018,280,1반,5,217.0,1052.0,20.6,11.0,254.0,양품
2,DIE-A-01,A,2018,280,1반,6,217.0,1052.0,20.6,11.0,257.0,양품
3,DIE-A-01,A,2018,280,1반,7,215.0,1038.0,20.9,11.0,250.0,양품
4,DIE-A-01,A,2018,280,1반,8,215.0,1038.0,20.9,11.0,258.0,양품
...,...,...,...,...,...,...,...,...,...,...,...,...
180,DIE-B-02,B,2021,320,2반,176,265.0,596.0,36.0,17.0,359.0,양품
181,DIE-B-02,B,2021,320,2반,178,264.0,595.0,36.0,17.0,355.0,양품
182,DIE-B-02,B,2021,320,2반,186,218.0,1054.0,21.4,2.0,253.0,불량
183,DIE-B-02,B,2021,320,2반,191,238.0,1152.0,91.2,13.0,254.0,불량
184,DIE-B-02,B,2021,320,2반,199,264.0,595.0,36.1,19.0,372.0,불량

In [16]:
three.merge(master, on='설비ID')

   샷      설비ID  비스킷두께 라인  도입연도  정격형체력 담당반
0  1  DIE-A-01   10.0  A  2018    280  1반
1  2  DIE-B-01   11.0  B  2020    320  2반
2  3  DIE-B-01   11.0  B  2020    320  2반

In [17]:
log.merge(master,on='설비ID')

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
0,1,DIE-A-01,214.0,1037.0,20.7,10.0,258.0,양품,A,2018,280,1반
1,2,DIE-B-01,217.0,1052.0,20.7,11.0,257.0,양품,B,2020,320,2반
2,3,DIE-B-01,214.0,1037.0,20.8,11.0,254.0,양품,B,2020,320,2반
3,4,DIE-B-02,217.0,1052.0,20.6,11.0,253.0,양품,B,2021,320,2반
4,5,DIE-A-01,217.0,1052.0,20.6,11.0,254.0,양품,A,2018,280,1반
...,...,...,...,...,...,...,...,...,...,...,...,...
180,196,DIE-A-01,264.0,594.0,76.3,19.0,381.0,불량,A,2018,280,1반
181,197,DIE-A-01,265.0,595.0,36.2,20.0,355.0,불량,A,2018,280,1반
182,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018,280,1반
183,199,DIE-B-02,264.0,595.0,36.1,19.0,372.0,불량,B,2021,320,2반
184,200,DIE-A-01,108.0,525.0,6170.0,15.0,237.0,불량,A,2018,280,1반

In [18]:
merged=log.merge(master,on='설비ID')

In [19]:
merged.shape

(185, 12)

In [21]:
m_inner=log.merge(master,on='설비ID', how='inner')

In [23]:
m_inner.shape

(185, 12)

In [22]:
m_left=log.merge(master,on='설비ID', how='left')

In [24]:
m_left.shape

(200, 12)

In [25]:
m_outer=log.merge(master,on='설비ID', how='outer')

In [26]:
m_outer.shape

(201, 12)

In [27]:
m_left.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인    도입연도  정격형체력 담당반
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품  A  2018.0  280.0  1반
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품  B  2020.0  320.0  2반
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품  B  2020.0  320.0  2반
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품  B  2021.0  320.0  2반
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품  A  2018.0  280.0  1반

In [28]:
m_left['라인']

0      A
1      B
2      B
3      B
4      A
      ..
195    A
196    A
197    A
198    B
199    A
Name: 라인, Length: 200, dtype: str

In [29]:
m_left['라인'].isna().sum()

np.int64(15)

In [31]:
m_left[m_left['라인'].isna()]['설비ID']

24     DIE-C-01
38     DIE-C-01
60     DIE-C-01
63     DIE-C-01
72     DIE-C-01
79     DIE-C-01
103    DIE-C-01
115    DIE-C-01
122    DIE-C-01
159    DIE-C-01
165    DIE-C-01
179    DIE-C-01
181    DIE-C-01
186    DIE-C-01
193    DIE-C-01
Name: 설비ID, dtype: str

In [32]:
# 실습1을 10시 30분까지

In [33]:
print(log.shape, master.shape)

(200, 8) (5, 5)

In [34]:
print(list(log.columns))
print(list(master.columns))

['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급']
['설비ID', '라인', '도입연도', '정격형체력', '담당반']

In [35]:
merged = log.merge(master, on="설비ID")

In [36]:
print(merged.shape)                        # (185, 12)   행이 15줄 줄었다
print(merged[["샷", "설비ID", "라인", "도입연도"]].head(2).to_string(index=False))

(185, 12)
 샷     설비ID 라인  도입연도
 1 DIE-A-01  A  2018
 2 DIE-B-01  B  2020

In [37]:
master.head()

       설비ID 라인  도입연도  정격형체력 담당반
0  DIE-A-01  A  2018    280  1반
1  DIE-A-02  A  2019    280  1반
2  DIE-B-01  B  2020    320  2반
3  DIE-B-02  B  2021    320  2반
4  DIE-D-01  D  2024    350  3반

In [38]:
master.iloc[0]

설비ID     DIE-A-01
라인              A
도입연도         2018
정격형체력         280
담당반            1반
Name: 0, dtype: object

In [40]:
master.iloc[[0,0,1]]

       설비ID 라인  도입연도  정격형체력 담당반
0  DIE-A-01  A  2018    280  1반
0  DIE-A-01  A  2018    280  1반
1  DIE-A-02  A  2019    280  1반

In [41]:
master.iloc[[0,0,1,2,3,4]]

       설비ID 라인  도입연도  정격형체력 담당반
0  DIE-A-01  A  2018    280  1반
0  DIE-A-01  A  2018    280  1반
1  DIE-A-02  A  2019    280  1반
2  DIE-B-01  B  2020    320  2반
3  DIE-B-02  B  2021    320  2반
4  DIE-D-01  D  2024    350  3반

In [42]:
master_dup=master.iloc[[0,0,1,2,3,4]]

In [44]:
master_dup['설비ID'].unique()

<ArrowStringArray>
['DIE-A-01', 'DIE-A-02', 'DIE-B-01', 'DIE-B-02', 'DIE-D-01']
Length: 5, dtype: str

In [45]:
master_dup['설비ID'].nunique()

5

In [46]:
log.merge(master_dup,on='설비ID')

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
0,1,DIE-A-01,214.0,1037.0,20.7,10.0,258.0,양품,A,2018,280,1반
1,1,DIE-A-01,214.0,1037.0,20.7,10.0,258.0,양품,A,2018,280,1반
2,2,DIE-B-01,217.0,1052.0,20.7,11.0,257.0,양품,B,2020,320,2반
3,3,DIE-B-01,214.0,1037.0,20.8,11.0,254.0,양품,B,2020,320,2반
4,4,DIE-B-02,217.0,1052.0,20.6,11.0,253.0,양품,B,2021,320,2반
...,...,...,...,...,...,...,...,...,...,...,...,...
243,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018,280,1반
244,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018,280,1반
245,199,DIE-B-02,264.0,595.0,36.1,19.0,372.0,불량,B,2021,320,2반
246,200,DIE-A-01,108.0,525.0,6170.0,15.0,237.0,불량,A,2018,280,1반
247,200,DIE-A-01,108.0,525.0,6170.0,15.0,237.0,불량,A,2018,280,1반

In [47]:
# 실습2 9시 42분까지

In [48]:
m_inner = log.merge(master, on="설비ID")                   # 기본 inner
m_left = log.merge(master, on="설비ID", how="left")
print(len(m_inner), len(m_left))          # 185 200
print(len(m_left) - len(m_inner))         # 15    사라진 줄 수

unmatched = m_left[m_left["라인"].isna()]   # 앞 단원 조건 필터 그대로
print(len(unmatched))                      # 15
print(unmatched["설비ID"].head(1).tolist())  # ['DIE-C-01']

185 200
15
15
['DIE-C-01']

In [50]:
log.iloc[:100].reset_index()

    index    샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0       0    1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1       1    2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2       2    3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3       3    4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4       4    5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품
..    ...  ...       ...    ...     ...    ...    ...    ...  ...
95     95   96  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
96     96   97  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
97     97   98  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
98     98   99  DIE-A-01    NaN     NaN    NaN    NaN    NaN   양품
99     99  100  DIE-A-02    NaN     NaN    NaN    NaN    NaN   양품

[100 rows x 9 columns]

In [51]:
log.iloc[:100].reset_index(drop=True)

      샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0     1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1     2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2     3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3     4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4     5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품
..  ...       ...    ...     ...    ...    ...    ...  ...
95   96  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
96   97  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
97   98  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
98   99  DIE-A-01    NaN     NaN    NaN    NaN    NaN   양품
99  100  DIE-A-02    NaN     NaN    NaN    NaN    NaN   양품

[100 rows x 8 columns]

In [52]:
part1=log.iloc[:100].reset_index(drop=True)

In [53]:
part2=log.iloc[100:].reset_index(drop=True)

In [54]:
part1.shape

(100, 8)

In [55]:
part2.shape

(100, 8)

In [56]:
pd.concat([part1,part2])

      샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0     1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1     2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2     3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3     4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4     5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..  ...       ...    ...     ...     ...    ...    ...  ...
95  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
96  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
97  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
98  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
99  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [57]:
stacked=pd.concat([part1,part2])

In [58]:
stacked.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=200)

In [60]:
stacked.index[97:100]

Index([97, 98, 99], dtype='int64')

In [59]:
stacked.index[-3:]

Index([97, 98, 99], dtype='int64')

In [61]:
pd.concat([part1,part2], ignore_index=True)

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [62]:
part1.shape

(100, 8)

In [63]:
part2.shape

(100, 8)

In [64]:
year = pd.concat([part1, part2], ignore_index=True)

In [65]:
year

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [66]:
report=year.merge(master,on='설비ID', how='left')

In [67]:
report.shape

(200, 12)

In [68]:
report.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인    도입연도  정격형체력 담당반
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품  A  2018.0  280.0  1반
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품  B  2020.0  320.0  2반
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품  B  2020.0  320.0  2반
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품  B  2021.0  320.0  2반
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품  A  2018.0  280.0  1반

In [70]:
report[report['라인'].isna()]

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
24,25,DIE-C-01,214.0,1037.0,20.7,11.0,257.0,양품,NaN,NaN,NaN,NaN
38,39,DIE-C-01,215.0,1040.0,20.9,11.0,257.0,양품,NaN,NaN,NaN,NaN
60,61,DIE-C-01,214.0,1037.0,20.6,11.0,254.0,양품,NaN,NaN,NaN,NaN
63,64,DIE-C-01,215.0,1040.0,20.6,11.0,254.0,양품,NaN,NaN,NaN,NaN
72,73,DIE-C-01,218.0,1057.0,21.2,13.0,257.0,양품,NaN,NaN,NaN,NaN
79,80,DIE-C-01,218.0,1054.0,21.3,14.0,253.0,양품,NaN,NaN,NaN,NaN
103,104,DIE-C-01,NaN,NaN,NaN,NaN,NaN,양품,NaN,NaN,NaN,NaN
115,116,DIE-C-01,265.0,595.0,34.0,17.0,355.0,양품,NaN,NaN,NaN,NaN
122,123,DIE-C-01,265.0,596.0,33.7,19.0,357.0,주의,NaN,NaN,NaN,NaN
159,160,DIE-C-01,264.0,595.0,35.8,18.0,381.0,양품,NaN,NaN,NaN,NaN
165,166,DIE-C-01,265.0,596.0,35.7,18.0,379.0,양품,NaN,NaN,NaN,NaN
179,180,DIE-C-01,265.0,596.0,36.2,18.0,382.0,양품,NaN,NaN,NaN,NaN
181,182,DIE-C-01,214.0,1036.0,93.1,12.0,247.0,불량,NaN,NaN,NaN,NaN
186,187,DIE-C-01,108.0,524.0,22.9,14.0,247.0,불량,NaN,NaN,NaN,NaN
193,194,DIE-C-01,113.0,255.0,34.4,19.0,370.0,불량,NaN,NaN,NaN,NaN

In [71]:
len(report[report['라인'].isna()])

15

In [ ]:
# 1 실습3 10시 25분까지

In [75]:
joined = log.merge(master, on="설비ID", how="left")   # ① 붙이기

In [76]:
joined.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인    도입연도  정격형체력 담당반
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품  A  2018.0  280.0  1반
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품  B  2020.0  320.0  2반
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품  B  2020.0  320.0  2반
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품  B  2021.0  320.0  2반
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품  A  2018.0  280.0  1반

In [77]:
with_line = joined[joined["라인"].notna()]

In [78]:
print(len(with_line))

185

In [79]:
not_ok = with_line[with_line["품질등급"] != "양품"]    # ③ 양품 아닌 줄만

In [80]:
print(len(not_ok))                                    # 34

34

In [81]:
result = not_ok.sort_values("비스킷두께", ascending=False)   # ④ 두꺼운 순

In [82]:
print(result[["샷", "설비ID", "라인", "비스킷두께", "품질등급"]].head(5).to_string(index=False))

  샷     설비ID 라인  비스킷두께 품질등급
198 DIE-A-01  A   27.0   불량
192 DIE-B-01  B   26.0   불량
 43 DIE-A-01  A   21.0   주의
197 DIE-A-01  A   20.0   불량
171 DIE-B-02  B   20.0   주의

In [73]:
#2 두 개의 주식 데이터를 보고 어떤 작업을 할지를 정하고, 두 주식 데이터를 병합해서 분석해보세요

In [74]:
# 3 연습문제 풀이

In [83]:
import numpy as np

In [84]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
list1= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [87]:
list1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [88]:
np.array(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
a=np.array(list1)

In [90]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [91]:
b=a[0:2,0:2]

In [92]:
c=a[1:,1:]

In [93]:
c

array([[5, 6],
       [8, 9]])

In [94]:
np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [95]:
arr=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [96]:
arr.shape

(2, 2, 3)

In [97]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.array([[1,2,3],[4,5,6]]).flatten()

array([1, 2, 3, 4, 5, 6])

In [100]:
a=np.arange(8)

In [ ]:
a

In [101]:
a.shape = (4,2)

In [102]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
# (df['나이'] > = 25) & (df['성별'] == '여자')

In [ ]:
# df[(df['나이'] >= 25) & (df['성별'] == '여자')]

In [103]:
import pandas as pd
df = pd.DataFrame({
    '이름': ['허준호', '이가원', '배규민', '고고림', '이새봄', '이보람', '이루리', '오다현'],
    '성별': ['남자', '여자', '남자', '남자', '여자', '여자', '여자', '여자'],
    '나이': [30, 24, 23, 21, 28, 26, 24, 24],
    '키': [183, 162, 179, 182, 160, 163, 157, 172]
})

In [104]:
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [108]:
help(df.describe)

Help on method describe in module pandas.core.generic:

describe(percentiles=None, include=None, exclude=None) -> Self method of pandas.DataFrame instance
    Generate descriptive statistics.

    Descriptive statistics include those that summarize the central
    tendency, dispersion and shape of a
    dataset's distribution, excluding ``NaN`` values.

    Analyzes both numeric and object series, as well
    as ``DataFrame`` column sets of mixed data types. The output
    will vary depending on what is provided. Refer to the notes
    below for more detail.

    Parameters
    ----------
    percentiles : list-like of numbers, optional
        The percentiles to include in the output. All should
        fall between 0 and 1. The default, ``None``, will automatically
        return the 25th, 50th, and 75th percentiles.
    include : 'all', list-like of dtypes or None (default), optional
        A white list of data types to include in the result. Ignored
        for ``Series``. Here are the options:

        - 'all' : All columns of the input will be included in the output.
        - A list-like of dtypes : Limits the results to the
          provided data types.
          To limit the result to numeric types submit
          ``numpy.number``. To limit it instead to object columns submit
          the ``numpy.object`` data type. Strings
          can also be used in the style of
          ``select_dtypes`` (e.g. ``df.describe(include=['O'])``). To
          select pandas categorical columns, use ``'category'``
        - None (default) : The result will include all numeric columns.
    exclude : list-like of dtypes or None (default), optional,
        A black list of data types to omit from the result. Ignored
        for ``Series``. Here are the options:

        - A list-like of dtypes : Excludes the provided data types
          from the result. To exclude numeric types submit
          ``numpy.number``. To exclude object columns submit the data
          type ``numpy.object``. Strings can also be used in the style of
          ``select_dtypes`` (e.g. ``df.describe(exclude=['O'])``). To
          exclude pandas categorical columns, use ``'category'``
        - None (default) : The result will exclude nothing.

    Returns
    -------
    Series or DataFrame
        Summary statistics of the Series or Dataframe provided.

    See Also
    --------
    DataFrame.count: Count number of non-NA/null observations.
    DataFrame.max: Maximum of the values in the object.
    DataFrame.min: Minimum of the values in the object.
    DataFrame.mean: Mean of the values.
    DataFrame.std: Standard deviation of the observations.
    DataFrame.select_dtypes: Subset of a DataFrame including/excluding
        columns based on their dtype.

    Notes
    -----
    For numeric data, the result's index will include ``count``,
    ``mean``, ``std``, ``min``, ``max`` as well as lower, ``50`` and
    upper percentiles. By default the lower percentile is ``25`` and the
    upper percentile is ``75``. The ``50`` percentile is the
    same as the median.

    For object data (e.g. strings), the result's index
    will include ``count``, ``unique``, ``top``, and ``freq``. The ``top``
    is the most common value. The ``freq`` is the most common value's
    frequency.

    If multiple object values have the highest count, then the
    ``count`` and ``top`` results will be arbitrarily chosen from
    among those with the highest count.

    For mixed data types provided via a ``DataFrame``, the default is to
    return only an analysis of numeric columns. If the DataFrame consists
    only of object and categorical data without any numeric columns, the
    default is to return an analysis of both the object and categorical
    columns. If ``include='all'`` is provided as an option, the result
    will include a union of attributes of each type.

    The `include` and `exclude` parameters can be used to limit
    which columns in a ``DataFrame`` are analyzed for the output.
    The parameters are ignored when analyzing a ``Series``.

    Examples
    --------
    Describing a numeric ``Series``.

    >>> s = pd.Series([1, 2, 3])
    >>> s.describe()
    count    3.0
    mean     2.0
    std      1.0
    min      1.0
    25%      1.5
    50%      2.0
    75%      2.5
    max      3.0
    dtype: float64

    Describing a categorical ``Series``.

    >>> s = pd.Series(["a", "a", "b", "c"])
    >>> s.describe()
    count     4
    unique    3
    top       a
    freq      2
    dtype: object

    Describing a timestamp ``Series``.

    >>> s = pd.Series(
    ...     [
    ...         np.datetime64("2000-01-01"),
    ...         np.datetime64("2010-01-01"),
    ...         np.datetime64("2010-01-01"),
    ...     ]
    ... )
    >>> s.describe()
    count                      3
    mean     2006-09-01 08:00:00
    min      2000-01-01 00:00:00
    25%      2004-12-31 12:00:00
    50%      2010-01-01 00:00:00
    75%      2010-01-01 00:00:00
    max      2010-01-01 00:00:00
    dtype: object

    Describing a ``DataFrame``. By default only numeric fields
    are returned.

    >>> df = pd.DataFrame(
    ...     {
    ...         "categorical": pd.Categorical(["d", "e", "f"]),
    ...         "numeric": [1, 2, 3],
    ...         "object": ["a", "b", "c"],
    ...     }
    ... )
    >>> df.describe()
           numeric
    count      3.0
    mean       2.0
    std        1.0
    min        1.0
    25%        1.5
    50%        2.0
    75%        2.5
    max        3.0

    Describing all columns of a ``DataFrame`` regardless of data type.

    >>> df.describe(include="all")  # doctest: +SKIP
           categorical  numeric object
    count            3      3.0      3
    unique           3      NaN      3
    top              f      NaN      a
    freq             1      NaN      1
    mean           NaN      2.0    NaN
    std            NaN      1.0    NaN
    min            NaN      1.0    NaN
    25%            NaN      1.5    NaN
    50%            NaN      2.0    NaN
    75%            NaN      2.5    NaN
    max            NaN      3.0    NaN

    Describing a column from a ``DataFrame`` by accessing it as
    an attribute.

    >>> df.numeric.describe()
    count    3.0
    mean     2.0
    std      1.0
    min      1.0
    25%      1.5
    50%      2.0
    75%      2.5
    max      3.0
    Name: numeric, dtype: float64

    Including only numeric columns in a ``DataFrame`` description.

    >>> df.describe(include=[np.number])
           numeric
    count      3.0
    mean       2.0
    std        1.0
    min        1.0
    25%        1.5
    50%        2.0
    75%        2.5
    max        3.0

    Including only string columns in a ``DataFrame`` description.

    >>> df.describe(include=[object])  # doctest: +SKIP
           object
    count       3
    unique      3
    top         a
    freq        1

    Including only categorical columns from a ``DataFrame`` description.

    >>> df.describe(include=["category"])
           categorical
    count            3
    unique           3
    top              d
    freq             1

    Excluding numeric columns from a ``DataFrame`` description.

    >>> df.describe(exclude=[np.number])  # doctest: +SKIP
           categorical object
    count            3      3
    unique           3      3
    top              f      a
    freq             1      1

    Excluding object columns from a ``DataFrame`` description.

    >>> df.describe(exclude=[object])  # doctest: +SKIP
           categorical  numeric
    count            3      3.0
    unique           3      NaN
    top              f      NaN
    freq             1      NaN
    mean           NaN      2.0
    std            NaN      1.0
    min            NaN      1.0
    25%            NaN      1.5
    50%            NaN      2.0
    75%            NaN      2.5
    max            NaN      3.0

In [110]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   성별      8 non-null      str
 2   나이      8 non-null      int64
 3   키       8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 508.0 bytes

In [109]:
df.describe(include='all')

         이름   성별         나이           키
count     8    8   8.000000    8.000000
unique    8    2        NaN         NaN
top     허준호   여자        NaN         NaN
freq      1    5        NaN         NaN
mean    NaN  NaN  25.000000  169.750000
std     NaN  NaN   2.878492   10.552589
min     NaN  NaN  21.000000  157.000000
25%     NaN  NaN  23.750000  161.500000
50%     NaN  NaN  24.000000  167.500000
75%     NaN  NaN  26.500000  179.750000
max     NaN  NaN  30.000000  183.000000

In [111]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [112]:
df.set_index('이름')

     성별  나이    키
이름
허준호  남자  30  183
이가원  여자  24  162
배규민  남자  23  179
고고림  남자  21  182
이새봄  여자  28  160
이보람  여자  26  163
이루리  여자  24  157
오다현  여자  24  172

In [113]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [114]:
df.set_index('이름', inplace=True)

In [115]:
df.index

Index(['허준호', '이가원', '배규민', '고고림', '이새봄', '이보람', '이루리', '오다현'], dtype='str', name='이름')

In [116]:
list1 =[[1,2],
        [3,4]]

In [117]:
np.array(list1)

array([[1, 2],
       [3, 4]])

In [118]:
arr=np.array(list1)

In [119]:
arr % 2 == 0

array([[False,  True],
       [False,  True]])

In [121]:
bool_index = (arr % 2 == 0)

In [122]:
bool_index

array([[False,  True],
       [False,  True]])

In [123]:
print('짝수\n', arr[bool_index])

짝수
 [2 4]

In [126]:
arr

array([[1, 2],
       [3, 4]])

In [127]:
arr[ :, 0  ]

array([1, 3])

In [128]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])

In [129]:
id(arr1)

1892459895600

In [130]:
arr2=arr1

In [131]:
id(arr2)

1892459895600

In [132]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
arr1[0,0]=10

In [135]:
arr1

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [136]:
arr2

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8]])